.POSIX:

CARGO    := cargo
BINARY   := target/release/imrule
TEST_DIR := test-e2e
TMP      := /tmp/imrule-e2e

.PHONY: all build check clean fmt fmt-fix install lint run test test-e2e test-e2e-skills uninstall

all: fmt lint test build

build:
	$(CARGO) build --release

check:
	$(CARGO) check

clean:
	$(CARGO) clean

fmt:
	$(CARGO) fmt -- --check

fmt-fix:
	$(CARGO) fmt

PREFIX   := $(HOME)/.local

install: build
	@mkdir -p $(PREFIX)/bin
	cp $(BINARY) $(PREFIX)/bin/imrule
	chmod +x $(PREFIX)/bin/imrule
	@echo "imrule installed to $(PREFIX)/bin/imrule"

install-system: PREFIX := /usr/local
install-system: build
	@mkdir -p $(PREFIX)/bin
	cp $(BINARY) $(PREFIX)/bin/imrule
	chmod +x $(PREFIX)/bin/imrule
	@echo "imrule installed to $(PREFIX)/bin/imrule (system-wide)"

uninstall:
	rm -f $(PREFIX)/bin/imrule

lint:
	$(CARGO) clippy -- -D warnings

run:
	$(CARGO) run -- $(ARGS)

test:
	$(CARGO) test

# ── End-to-end tests ──────────────────────────────────────────────
test-e2e: build
	@echo ""; echo "━━━ E2E: imrule init (local) ━━━"
	rm -rf $(TMP)/init-local && mkdir -p $(TMP)/init-local
	$(BINARY) init --project-root $(TMP)/init-local
	@test -d $(TMP)/init-local/.imrule            && echo "[PASS] .imrule directory created"   || (echo "[FAIL] .imrule directory missing"   && exit 1)
	@test -f $(TMP)/init-local/.imrule/imrule.toml && echo "[PASS] imrule.toml created"        || (echo "[FAIL] imrule.toml missing"         && exit 1)
	@test -f $(TMP)/init-local/.imrule/AGENTS.md  && echo "[PASS] AGENTS.md created"          || (echo "[FAIL] AGENTS.md missing"           && exit 1)
	@echo ""; echo "━━━ E2E: imrule init --global ━━━"
	rm -rf $(TMP)/init-global && mkdir -p $(TMP)/init-global
	XDG_CONFIG_HOME=$(TMP)/init-global $(BINARY) init --global
	@test -d $(TMP)/init-global/imrule            && echo "[PASS] global dir created"         || (echo "[FAIL] global dir missing"          && exit 1)
	@test -f $(TMP)/init-global/imrule/imrule.toml && echo "[PASS] global imrule.toml created" || (echo "[FAIL] global imrule.toml missing"  && exit 1)
	@test -f $(TMP)/init-global/imrule/AGENTS.md  && echo "[PASS] global AGENTS.md created"   || (echo "[FAIL] global AGENTS.md missing"    && exit 1)
	@echo ""; echo "━━━ E2E: imrule init (idempotent) ━━━"
	$(BINARY) init --project-root $(TMP)/init-local
	@grep -q "ImRule Configuration File" $(TMP)/init-local/.imrule/imrule.toml && echo "[PASS] init did not overwrite existing files" || (echo "[FAIL] init overwrote existing files" && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply (all agents) ━━━"
	rm -rf $(TMP)/apply-all && cp -r $(TEST_DIR) $(TMP)/apply-all
	$(BINARY) apply --project-root $(TMP)/apply-all --verbose
	@test -f $(TMP)/apply-all/CLAUDE.md                                    && echo "[PASS] CLAUDE.md generated"        || (echo "[FAIL] CLAUDE.md missing"           && exit 1)
	@test -f $(TMP)/apply-all/.github/copilot-instructions.md             && echo "[PASS] copilot instructions generated" || (echo "[FAIL] copilot instructions missing" && exit 1)
	@grep -q "Generated by ImRule" $(TMP)/apply-all/CLAUDE.md             && echo "[PASS] CLAUDE.md has marker"      || (echo "[FAIL] CLAUDE.md missing marker"    && exit 1)
	@grep -q "Source:" $(TMP)/apply-all/CLAUDE.md                         && echo "[PASS] CLAUDE.md has source comment" || (echo "[FAIL] CLAUDE.md missing source"   && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply --dry-run ━━━"
	rm -rf $(TMP)/apply-dryrun && cp -r $(TEST_DIR) $(TMP)/apply-dryrun
	$(BINARY) apply --project-root $(TMP)/apply-dryrun --dry-run --verbose
	@test ! -f $(TMP)/apply-dryrun/CLAUDE.md                              && echo "[PASS] dry-run did not write files" || (echo "[FAIL] dry-run wrote files"         && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply --agents claude ━━━"
	rm -rf $(TMP)/apply-single && cp -r $(TEST_DIR) $(TMP)/apply-single
	$(BINARY) apply --project-root $(TMP)/apply-single --agents claude --verbose
	@test  -f $(TMP)/apply-single/CLAUDE.md                               && echo "[PASS] CLAUDE.md generated"        || (echo "[FAIL] CLAUDE.md missing"           && exit 1)
	@test ! -f $(TMP)/apply-single/.github/copilot-instructions.md        && echo "[PASS] copilot not generated"      || (echo "[FAIL] copilot should not exist"    && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply --agents claude,copilot ━━━"
	rm -rf $(TMP)/apply-multi && cp -r $(TEST_DIR) $(TMP)/apply-multi
	$(BINARY) apply --project-root $(TMP)/apply-multi --agents claude,copilot --verbose
	@test -f $(TMP)/apply-multi/CLAUDE.md                                 && echo "[PASS] CLAUDE.md generated"        || (echo "[FAIL] CLAUDE.md missing"           && exit 1)
	@test -f $(TMP)/apply-multi/.github/copilot-instructions.md           && echo "[PASS] copilot instructions generated" || (echo "[FAIL] copilot instructions missing" && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply (no MCP config present) ━━━"
	rm -rf $(TMP)/apply-nomcp && cp -r $(TEST_DIR) $(TMP)/apply-nomcp
	$(BINARY) apply --project-root $(TMP)/apply-nomcp --agents claude --verbose
	@test -f $(TMP)/apply-nomcp/CLAUDE.md                                 && echo "[PASS] CLAUDE.md generated"        || (echo "[FAIL] CLAUDE.md missing"           && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply (MCP merge) ━━━"
	rm -rf $(TMP)/apply-mcp && cp -r $(TEST_DIR) $(TMP)/apply-mcp
	cp test-e2e/claude_desktop_config.json $(TMP)/apply-mcp/claude_desktop_config.json 2>/dev/null || true
	$(BINARY) apply --project-root $(TMP)/apply-mcp --agents claude --verbose
	@test -f $(TMP)/apply-mcp/CLAUDE.md                                   && echo "[PASS] CLAUDE.md generated"        || (echo "[FAIL] CLAUDE.md missing"           && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply --backup (creates .bak) ━━━"
	rm -rf $(TMP)/apply-backup && cp -r $(TEST_DIR) $(TMP)/apply-backup
	printf "# original\n" > $(TMP)/apply-backup/CLAUDE.md
	$(BINARY) apply --project-root $(TMP)/apply-backup --agents claude --backup
	@test -f $(TMP)/apply-backup/CLAUDE.md.bak                            && echo "[PASS] .bak created"              || (echo "[FAIL] .bak missing"                && exit 1)
	@grep -q "original" $(TMP)/apply-backup/CLAUDE.md.bak                 && echo "[PASS] .bak has original content" || (echo "[FAIL] .bak content wrong"          && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply (no --backup, no .bak) ━━━"
	rm -rf $(TMP)/apply-nobak && cp -r $(TEST_DIR) $(TMP)/apply-nobak
	printf "# original\n" > $(TMP)/apply-nobak/CLAUDE.md
	$(BINARY) apply --project-root $(TMP)/apply-nobak --agents claude
	@test ! -f $(TMP)/apply-nobak/CLAUDE.md.bak                           && echo "[PASS] no .bak created"           || (echo "[FAIL] .bak should not exist"       && exit 1)
	@echo ""; echo "━━━ E2E: imrule apply (gitignore) ━━━"
	rm -rf $(TMP)/apply-gitignore && cp -r $(TEST_DIR) $(TMP)/apply-gitignore
	touch $(TMP)/apply-gitignore/.gitignore
	$(BINARY) apply --project-root $(TMP)/apply-gitignore --agents claude --verbose
	@grep -q "ImRule Generated Files" $(TMP)/apply-gitignore/.gitignore   && echo "[PASS] .gitignore updated"        || (echo "[FAIL] .gitignore not updated"      && exit 1)
	@echo ""; echo "━━━ E2E: imrule revert (basic) ━━━"
	rm -rf $(TMP)/revert-basic && cp -r $(TEST_DIR) $(TMP)/revert-basic
	$(BINARY) apply --project-root $(TMP)/revert-basic --agents claude
	@test -f $(TMP)/revert-basic/CLAUDE.md                                && echo "[PASS] CLAUDE.md exists"          || (echo "[FAIL] CLAUDE.md missing"           && exit 1)
	$(BINARY) revert --project-root $(TMP)/revert-basic --agents claude
	@test ! -f $(TMP)/revert-basic/CLAUDE.md                              && echo "[PASS] CLAUDE.md removed"         || (echo "[FAIL] CLAUDE.md still exists"      && exit 1)
	@echo ""; echo "━━━ E2E: imrule revert --dry-run ━━━"
	rm -rf $(TMP)/revert-dryrun && cp -r $(TEST_DIR) $(TMP)/revert-dryrun
	$(BINARY) apply --project-root $(TMP)/revert-dryrun --agents claude
	$(BINARY) revert --project-root $(TMP)/revert-dryrun --agents claude --dry-run
	@test -f $(TMP)/revert-dryrun/CLAUDE.md                               && echo "[PASS] file not removed on dry-run" || (echo "[FAIL] file removed on dry-run"    && exit 1)
	@echo ""; echo "━━━ E2E: error on unknown agent ━━━"
	rm -rf $(TMP)/err-agent && cp -r $(TEST_DIR) $(TMP)/err-agent
	$(BINARY) apply --project-root $(TMP)/err-agent --agents nonexistent 2>/dev/null && (echo "[FAIL] should have errored" && exit 1) || echo "[PASS] error on unknown agent"
	@echo ""; echo "━━━ E2E: all tests passed ━━━"

# ── End-to-end skills tests ──────────────────────────────────────
SKILLS_FIXTURE := test-e2e-skills/fixture-local-source

test-e2e-skills: build
	@echo ""; echo "━━━ E2E Skills: imrule skills add (local source) ━━━"
	rm -rf $(TMP)/skills-local && mkdir -p $(TMP)/skills-local/.imrule
	printf "# Rules\n" > $(TMP)/skills-local/.imrule/AGENTS.md
	$(BINARY) skills add $(SKILLS_FIXTURE) --project-root $(TMP)/skills-local
	@test -d $(TMP)/skills-local/.imrule/skills/sample-skill                     && echo "[PASS] sample-skill installed to .imrule/skills"         || (echo "[FAIL] sample-skill missing"          && exit 1)
	@test -f $(TMP)/skills-local/.imrule/skills/sample-skill/SKILL.md            && echo "[PASS] sample-skill has SKILL.md"                       || (echo "[FAIL] sample-skill SKILL.md missing" && exit 1)
	@test -d $(TMP)/skills-local/.imrule/skills/another-skill                    && echo "[PASS] another-skill installed to .imrule/skills"        || (echo "[FAIL] another-skill missing"         && exit 1)
	@echo ""; echo "━━━ E2E Skills: skill propagated to agent dirs ━━━"
	@test -d $(TMP)/skills-local/.claude/skills/sample-skill                     && echo "[PASS] sample-skill propagated to .claude/skills"        || (echo "[FAIL] sample-skill not in .claude"   && exit 1)
	@test -d $(TMP)/skills-local/.codex/skills/sample-skill                      && echo "[PASS] sample-skill propagated to .codex/skills"         || (echo "[FAIL] sample-skill not in .codex"    && exit 1)
	@echo ""; echo "━━━ E2E Skills: imrule skills add --list ━━━"
	rm -rf $(TMP)/skills-list && mkdir -p $(TMP)/skills-list
	$(BINARY) skills add $(SKILLS_FIXTURE) --list --project-root $(TMP)/skills-list | grep -q "sample-skill" \
		&& echo "[PASS] --list shows sample-skill" \
		|| (echo "[FAIL] --list did not show sample-skill" && exit 1)
	@test ! -d $(TMP)/skills-list/.imrule/skills                                && echo "[PASS] --list did not install"                         || (echo "[FAIL] --list installed skills"       && exit 1)
	@echo ""; echo "━━━ E2E Skills: imrule skills add --skill (selective) ━━━"
	rm -rf $(TMP)/skills-filter && mkdir -p $(TMP)/skills-filter/.imrule
	printf "# Rules\n" > $(TMP)/skills-filter/.imrule/AGENTS.md
	$(BINARY) skills add $(SKILLS_FIXTURE) --skill sample-skill --project-root $(TMP)/skills-filter
	@test -d $(TMP)/skills-filter/.imrule/skills/sample-skill                     && echo "[PASS] sample-skill installed"                         || (echo "[FAIL] sample-skill missing"          && exit 1)
	@test ! -d $(TMP)/skills-filter/.imrule/skills/another-skill                  && echo "[PASS] another-skill NOT installed (--skill filter)"    || (echo "[FAIL] another-skill should not exist" && exit 1)
	@echo ""; echo "━━━ E2E Skills: imrule skills list ━━━"
	$(BINARY) skills list --project-root $(TMP)/skills-local | grep -q "sample-skill" \
		&& echo "[PASS] skills list shows installed skill" \
		|| (echo "[FAIL] skills list did not show skill" && exit 1)
	@echo ""; echo "━━━ E2E Skills: imrule skills add (remote GitHub source) ━━━"
	rm -rf $(TMP)/skills-remote && mkdir -p $(TMP)/skills-remote/.imrule
	printf "# Rules\n" > $(TMP)/skills-remote/.imrule/AGENTS.md
	$(BINARY) skills add vercel-labs/agent-skills --project-root $(TMP)/skills-remote 2>&1 | tee $(TMP)/skills-remote/log.txt
	@grep -q "Installed" $(TMP)/skills-remote/log.txt                             && echo "[PASS] remote skills installed"                        || (echo "[FAIL] remote skills not installed"   && exit 1)
	@test -d $(TMP)/skills-remote/.imrule/skills                                 && echo "[PASS] .imrule/skills directory created from remote"    || (echo "[FAIL] .imrule/skills missing"        && exit 1)
	@echo ""; echo "━━━ E2E Skills: all skills tests passed ━━━"
