//! Shared constants for the native Rust CLI.

/// Package name used by the Rust crate during migration.
pub const PACKAGE_NAME: &str = env!("CARGO_PKG_NAME");

/// Package version exposed by the native Rust crate.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Default rules filename used by Ruler.
pub const DEFAULT_RULES_FILENAME: &str = "AGENTS.md";

/// Standard diagnostic prefix used by the existing CLI.
pub const ERROR_PREFIX: &str = "[imrule] Error:";

pub const SKILLS_DIR: &str = "skills";
pub const RULER_SKILLS_PATH: &str = ".imrule/skills";
pub const CLAUDE_SKILLS_PATH: &str = ".claude/skills";
pub const CODEX_SKILLS_PATH: &str = ".codex/skills";
pub const OPENCODE_SKILLS_PATH: &str = ".opencode/skills";
pub const PI_SKILLS_PATH: &str = ".pi/skills";
pub const GOOSE_SKILLS_PATH: &str = ".agents/skills";
pub const VIBE_SKILLS_PATH: &str = ".vibe/skills";
pub const ROO_SKILLS_PATH: &str = ".roo/skills";
pub const GEMINI_SKILLS_PATH: &str = ".gemini/skills";
pub const JUNIE_SKILLS_PATH: &str = ".junie/skills";
pub const CURSOR_SKILLS_PATH: &str = ".cursor/skills";
pub const WINDSURF_SKILLS_PATH: &str = ".windsurf/skills";
pub const FACTORY_SKILLS_PATH: &str = ".factory/skills";
pub const ANTIGRAVITY_SKILLS_PATH: &str = ".agent/skills";
pub const SKILL_MD_FILENAME: &str = "SKILL.md";

pub const RULER_SUBAGENTS_PATH: &str = ".imrule/agents";
pub const CLAUDE_SUBAGENTS_PATH: &str = ".claude/agents";
pub const CURSOR_SUBAGENTS_PATH: &str = ".cursor/agents";
pub const CODEX_SUBAGENTS_PATH: &str = ".codex/agents";
pub const COPILOT_SUBAGENTS_PATH: &str = ".github/agents";

pub const GENERATED_BY_RULER_MARKER: &str = "<!-- Generated by ImRule -->";

/// Returns the XDG config home directory.
pub fn xdg_config_home() -> std::path::PathBuf {
    std::env::var_os("XDG_CONFIG_HOME")
        .map(std::path::PathBuf::from)
        .or_else(|| {
            std::env::var_os("HOME").map(|home| std::path::PathBuf::from(home).join(".config"))
        })
        .unwrap_or_else(|| std::path::PathBuf::from(".config"))
}

/// Normalizes path separators to forward slashes for consistent output.
pub fn normalize_path_separators(path: &str) -> String {
    path.replace('\\', "/")
}
