// @generated by scripts/shipped-skills.py from the release tags; do not edit.
//! Every built-in skill revision a release installed: where, and each
//! file's [`content_digest`](super::builtin_skills::content_digest).

use super::builtin_skills::ShippedRevision;

pub const SHIPPED_BUILTIN_REVISIONS: &[ShippedRevision] = &[
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "ci/github-actions",
        revision: 1,
        files: &[
            ("SKILL.md", 0x6fabe6ef278bce01),
            ("references/convention.md", 0x2913aefefe5a531e),
            ("references/structure.md", 0x12d60750920f6bd4),
            ("references/templates/ci-node.yml.tmpl", 0x37dd23dc6c9e3081),
            (
                "references/templates/ci-python.yml.tmpl",
                0x87ae626dc4b46d23,
            ),
            ("references/templates/ci-rust.yml.tmpl", 0xf11a33ab9e27fc1b),
            (
                "references/templates/dependabot.yml.tmpl",
                0xf5d04c2aa91fe052,
            ),
            (
                "references/templates/release-image.yml.tmpl",
                0x3c434b0386cdbe28,
            ),
            (
                "references/templates/release-python.yml.tmpl",
                0xe6f41445e4146ea4,
            ),
            (
                "references/templates/release-rust.yml.tmpl",
                0xef2357f7d83c7839,
            ),
            ("scripts/check.py", 0x08cb126a732c98b1),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "cli",
        revision: 1,
        files: &[
            ("SKILL.md", 0x48051a148ab6353a),
            ("references/convention.md", 0xfa9b39605d34279f),
            ("references/structure.md", 0x9352333b93297e85),
            ("scripts/check.py", 0xdee955e8f7bc9ff2),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "docker/optimize",
        revision: 1,
        files: &[
            ("SKILL.md", 0x80634196754c2fca),
            ("references/convention.md", 0xd297a0e1ecca9b4a),
            ("references/official-sources.md", 0xffa23d7287a0f798),
            ("references/structure.md", 0x04bb1763502d80b8),
            ("scripts/check.py", 0x3ad9f4212c25f517),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "docker/setup",
        revision: 1,
        files: &[
            ("SKILL.md", 0x0c6f61c61ebb84e8),
            ("references/convention.md", 0xd1d51324b60aa830),
            ("references/structure.md", 0x0f22a97206be6fe9),
            (
                "references/templates/Dockerfile.python-server.tmpl",
                0xb59d069ba4abfca9,
            ),
            (
                "references/templates/Dockerfile.rust-server.tmpl",
                0x77b436a7c9046061,
            ),
            (
                "references/templates/Makefile.docker.tmpl",
                0x68025d3585236216,
            ),
            ("references/templates/compose.yaml.tmpl", 0x49b344068afaf959),
            ("references/templates/dockerignore.tmpl", 0x0d8ae09be3506bc3),
            ("scripts/check.py", 0xb49bfe232734a83f),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "imrule-issue",
        revision: 2,
        files: &[
            ("SKILL.md", 0xed335d33551f1a7e),
            ("references/convention.md", 0xc3a41b053401a900),
            ("references/structure.md", 0x97db11b6451a8d36),
            ("scripts/check.py", 0xbd27554c0de220fb),
            ("scripts/collect.py", 0x162d66be02662431),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "make/setup",
        revision: 1,
        files: &[
            ("SKILL.md", 0xe8be6b1786d33c5c),
            ("references/convention.md", 0x9be496b524dea7a8),
            ("references/structure.md", 0x63b2f2187cbfd5a0),
            (
                "references/templates/python-cli.mk.tmpl",
                0xbd762c444e772014,
            ),
            (
                "references/templates/python-server.mk.tmpl",
                0x00dd13fe43855db5,
            ),
            ("references/templates/rust-cli.mk.tmpl", 0x2f858b428b7440f7),
            (
                "references/templates/rust-server.mk.tmpl",
                0x0e061481547bbf4e,
            ),
            ("scripts/check.py", 0xb36138d8e7047124),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "python/cli",
        revision: 1,
        files: &[
            ("SKILL.md", 0xd55adc5b210ddfe3),
            ("references/convention.md", 0x638082a0318aad51),
            ("references/structure.md", 0x3db43ac5f0fafbcc),
            ("scripts/check.py", 0x34358cfc984d61bb),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "python/server",
        revision: 1,
        files: &[
            ("SKILL.md", 0xcbb0fcdda6c4bfaf),
            ("references/convention.md", 0xe8c67a5fd075a3e0),
            ("references/structure.md", 0x83b7c205e3fb76b7),
            ("scripts/check.py", 0xe9a0dd2f047b818f),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "release/versioning",
        revision: 1,
        files: &[
            ("SKILL.md", 0x61d591f62d278669),
            ("references/convention.md", 0xa8f06fab93232523),
            ("references/structure.md", 0xac5dd85624ef8f9e),
            ("references/templates/CHANGELOG.md.tmpl", 0xc154f98157cfd0cb),
            ("references/templates/build.rs.tmpl", 0xff6d65e10958df0f),
            ("scripts/check.py", 0xf2f0530bc3e149f7),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "rust/cli",
        revision: 1,
        files: &[
            ("SKILL.md", 0xfe5c9e361572ba23),
            ("references/convention.md", 0x95ffad29858e1a43),
            ("references/structure.md", 0xfc625c5c472ed6cb),
            ("scripts/check.py", 0xa4b43d6d608c5d6b),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "rust/server",
        revision: 1,
        files: &[
            ("SKILL.md", 0x9ce069a07b062025),
            ("references/convention.md", 0xd94ffbae520e3ffa),
            ("references/structure.md", 0x35a53dbc0e764a32),
            ("scripts/check.py", 0xa8174d4ad4064ca7),
        ],
    },
    // v0.5.0.0, v0.5.1.0
    ShippedRevision {
        path: "server",
        revision: 1,
        files: &[
            ("SKILL.md", 0x22d200c8e0c3177e),
            ("references/convention.md", 0x667ffd77f52d9053),
            ("references/structure.md", 0xf90aef01115d4741),
            ("scripts/check.py", 0x6458e94894b94321),
        ],
    },
    // v0.5.0.0
    ShippedRevision {
        path: "vscode/setup",
        revision: 1,
        files: &[
            ("SKILL.md", 0xc43cde0afcb894dc),
            ("references/convention.md", 0x0972c43543f17f2e),
            ("references/structure.md", 0x7916f66213035c30),
            (
                "references/templates/extensions.python.json.tmpl",
                0x58956c866bc072ea,
            ),
            (
                "references/templates/extensions.rust.json.tmpl",
                0x190508926dad742d,
            ),
            (
                "references/templates/launch.python-cli.json.tmpl",
                0x052de2589ce22f54,
            ),
            (
                "references/templates/launch.python-server.json.tmpl",
                0xe5eb7be0934792c8,
            ),
            (
                "references/templates/launch.rust-cli.json.tmpl",
                0x0e29ee6521f51009,
            ),
            (
                "references/templates/launch.rust-server.json.tmpl",
                0xbf2eef44b27b0ca1,
            ),
            (
                "references/templates/settings.python.json.tmpl",
                0x9d1b2798b53d3d7e,
            ),
            (
                "references/templates/settings.rust.json.tmpl",
                0x351e02b1f6527431,
            ),
            (
                "references/templates/tasks.python.json.tmpl",
                0x9ac6556bc136afdd,
            ),
            (
                "references/templates/tasks.rust.json.tmpl",
                0x033b70dbdf45b418,
            ),
            ("scripts/check.py", 0xb685504bba39fad7),
        ],
    },
    // v0.5.1.0
    ShippedRevision {
        path: "vscode/setup",
        revision: 2,
        files: &[
            ("SKILL.md", 0x902beb4696acecf5),
            ("references/convention.md", 0xb1d5714e377e629e),
            ("references/structure.md", 0x3d1ad693acbb2520),
            (
                "references/templates/extensions.python.json.tmpl",
                0x58956c866bc072ea,
            ),
            (
                "references/templates/extensions.rust.json.tmpl",
                0x190508926dad742d,
            ),
            (
                "references/templates/launch.python-cli.json.tmpl",
                0x052de2589ce22f54,
            ),
            (
                "references/templates/launch.python-server.json.tmpl",
                0xe5eb7be0934792c8,
            ),
            (
                "references/templates/launch.rust-cli.json.tmpl",
                0x0e29ee6521f51009,
            ),
            (
                "references/templates/launch.rust-server.json.tmpl",
                0xbf2eef44b27b0ca1,
            ),
            (
                "references/templates/settings.python.json.tmpl",
                0x9d1b2798b53d3d7e,
            ),
            (
                "references/templates/settings.rust.json.tmpl",
                0x351e02b1f6527431,
            ),
            (
                "references/templates/tasks.port-guard.json.tmpl",
                0xb3d0b479bd2b22dc,
            ),
            (
                "references/templates/tasks.python.json.tmpl",
                0x9ac6556bc136afdd,
            ),
            (
                "references/templates/tasks.rust.json.tmpl",
                0x033b70dbdf45b418,
            ),
            ("scripts/check.py", 0x84f93326c1d5c40b),
        ],
    },
];
