use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

#[test]
fn cli_version_and_help_are_release_ready() {
    let version = Command::cargo_bin("ruler")
        .unwrap()
        .arg("--version")
        .output()
        .unwrap();
    assert!(version.status.success());
    assert!(String::from_utf8_lossy(&version.stdout).contains("ruler 0.4.0"));

    let help = Command::cargo_bin("ruler")
        .unwrap()
        .arg("apply")
        .arg("--help")
        .output()
        .unwrap();
    assert!(help.status.success());
    let stdout = String::from_utf8_lossy(&help.stdout);
    assert!(stdout.contains("Apply ruler configurations to supported AI agents"));
    assert!(stdout.contains("--project-root"));
    assert!(stdout.contains("--no-mcp"));
    assert!(stdout.contains("agentsmd, aider, amazonqcli"));
}

#[test]
fn apply_and_revert_are_native_rust_commands() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Always be concise.").unwrap();

    Command::cargo_bin("ruler")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
            "--no-mcp",
        ])
        .assert()
        .success();

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.starts_with("<!-- Generated by Ruler -->"));
    assert!(claude.contains("Always be concise."));
    assert!(tmp.path().join(".clinerules").is_file());

    Command::cargo_bin("ruler")
        .unwrap()
        .args([
            "revert",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
    assert!(!tmp.path().join(".clinerules").exists());
}

#[test]
fn apply_dry_run_does_not_write_outputs() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Dry run only.").unwrap();

    Command::cargo_bin("ruler")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--no-mcp",
            "--dry-run",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn init_scaffolds_ruler_files_without_overwriting_existing_content() {
    let tmp = tempdir().unwrap();

    let init = Command::cargo_bin("ruler")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .output()
        .unwrap();
    assert!(init.status.success());
    assert!(String::from_utf8_lossy(&init.stdout).contains("Ruler initialized"));

    let agents = tmp.path().join(".ruler/AGENTS.md");
    let toml = tmp.path().join(".ruler/ruler.toml");
    assert!(fs::read_to_string(&agents)
        .unwrap()
        .contains("Centralised AI agent instructions"));
    assert!(fs::read_to_string(&toml)
        .unwrap()
        .contains("default_agents"));

    fs::write(&agents, "custom").unwrap();
    Command::cargo_bin("ruler")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .assert()
        .success();
    assert_eq!(fs::read_to_string(&agents).unwrap(), "custom");
}

#[test]
fn init_global_uses_xdg_config_home() {
    let tmp = tempdir().unwrap();

    Command::cargo_bin("ruler")
        .unwrap()
        .env("XDG_CONFIG_HOME", tmp.path())
        .args(["init", "--global"])
        .assert()
        .success();

    assert!(tmp.path().join("ruler/AGENTS.md").is_file());
    assert!(tmp.path().join("ruler/ruler.toml").is_file());
}
