use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

#[test]
fn cli_version_and_help_are_release_ready() {
    let version = Command::cargo_bin("imrule")
        .unwrap()
        .arg("--version")
        .output()
        .unwrap();
    assert!(version.status.success());
    assert!(String::from_utf8_lossy(&version.stdout).contains("imrule 0.1.0"));

    let help = Command::cargo_bin("imrule")
        .unwrap()
        .arg("apply")
        .arg("--help")
        .output()
        .unwrap();
    assert!(help.status.success());
    let stdout = String::from_utf8_lossy(&help.stdout);
    assert!(stdout.contains("Apply imrule configurations to supported AI agents"));
    assert!(stdout.contains("--project-root"));
    assert!(stdout.contains("--dry-run"));
    assert!(stdout.contains("agentsmd, aider, amazonqcli"));
}

#[test]
fn apply_and_clear_are_native_rust_commands() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Always be concise.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
        ])
        .assert()
        .success();

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.starts_with("<!-- Generated by ImRule -->"));
    assert!(claude.contains("Always be concise."));
    assert!(tmp.path().join(".clinerules").is_file());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
    assert!(!tmp.path().join(".clinerules").exists());
}

#[test]
fn apply_collapses_gjc_paths_to_dot_gjc_in_gitignore() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "GJC rules.").unwrap();
    fs::write(
        tmp.path().join(".imrule/mcp.json"),
        r#"{"mcpServers":{"gjc-tool":{"command":"node","args":["gjc-tool.js"]}}}"#,
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "gjc",
        ])
        .assert()
        .success();

    assert!(tmp.path().join(".gjc/RULES.md").is_file());
    assert!(tmp.path().join(".gjc/mcp.json").is_file());
    let mcp: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(tmp.path().join(".gjc/mcp.json")).unwrap())
            .unwrap();
    assert!(mcp["mcpServers"]["gjc-tool"].is_object());

    let gitignore = fs::read_to_string(tmp.path().join(".gitignore")).unwrap();
    assert!(
        gitignore.contains("/.gjc\n") || gitignore.contains("/.gjc/\n"),
        "expected .gitignore to contain /.gjc, got:\n{gitignore}"
    );
    assert!(
        !gitignore.contains("/.gjc/RULES.md"),
        "expected .gitignore to collapse .gjc/* paths, got:\n{gitignore}"
    );

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "gjc",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join(".gjc/RULES.md").exists());
    assert!(!tmp.path().join(".gjc/mcp.json").exists());
}

#[test]
fn apply_dry_run_does_not_write_outputs() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Dry run only.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--dry-run",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn init_scaffolds_imrule_files_without_overwriting_existing_content() {
    let tmp = tempdir().unwrap();

    let init = Command::cargo_bin("imrule")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .output()
        .unwrap();
    assert!(init.status.success());
    assert!(String::from_utf8_lossy(&init.stdout).contains("ImRule initialized"));

    let agents = tmp.path().join(".imrule/AGENTS.md");
    let toml = tmp.path().join(".imrule/imrule.toml");
    assert!(fs::read_to_string(&agents)
        .unwrap()
        .contains("Centralised AI agent instructions"));
    assert!(fs::read_to_string(&toml)
        .unwrap()
        .contains("default_agents"));

    fs::write(&agents, "custom").unwrap();
    Command::cargo_bin("imrule")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .assert()
        .success();
    assert_eq!(fs::read_to_string(&agents).unwrap(), "custom");
}

#[test]
fn init_global_uses_xdg_config_home() {
    let tmp = tempdir().unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .env("XDG_CONFIG_HOME", tmp.path())
        .args(["init", "--global"])
        .assert()
        .success();

    assert!(tmp.path().join("imrule/AGENTS.md").is_file());
    assert!(tmp.path().join("imrule/imrule.toml").is_file());
}

#[test]
fn apply_works_with_legacy_ruler_directory() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Legacy ruler rules.").unwrap();

    let output = Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .output()
        .unwrap();
    assert!(output.status.success());

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.starts_with("<!-- Generated by ImRule -->"));
    assert!(claude.contains("Legacy ruler rules."));

    // Should print deprecation warning to stderr.
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("legacy '.ruler/' directory"));
}

#[test]
fn apply_prefers_imrule_over_ruler_when_both_exist() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "New rules.").unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Old rules.").unwrap();

    let output = Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .output()
        .unwrap();
    assert!(output.status.success());

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.contains("New rules."));
    assert!(!claude.contains("Old rules."));

    // No deprecation warning when .imrule exists.
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(!stderr.contains("legacy"));
}

#[test]
fn clear_removes_generated_files_and_preserves_imrule_dir_by_default() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Clear test rules.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
        ])
        .assert()
        .success();

    assert!(tmp.path().join("CLAUDE.md").exists());
    assert!(tmp.path().join(".clinerules").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
        ])
        .assert()
        .success();

    // Generated files removed.
    assert!(!tmp.path().join("CLAUDE.md").exists());
    assert!(!tmp.path().join(".clinerules").exists());

    // .imrule/ preserved by default.
    assert!(tmp.path().join(".imrule").exists());
    assert!(tmp.path().join(".imrule/AGENTS.md").exists());
}

#[test]
fn clear_dry_run_does_not_remove_files() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Dry clear.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    assert!(tmp.path().join("CLAUDE.md").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--dry-run",
        ])
        .assert()
        .success();

    // File should still exist after dry run.
    assert!(tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn clear_remove_source_also_deletes_imrule_dir() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Remove source test.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--remove-source",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
    assert!(!tmp.path().join(".imrule").exists());
}

#[test]
fn clear_skips_non_generated_files() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Safety check.").unwrap();
    // Write a CLAUDE.md without the imrule marker — should not be removed.
    fs::write(tmp.path().join("CLAUDE.md"), "# My own instructions\n").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    // User-owned file must survive.
    assert!(tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn apply_skips_agent_when_disabled_in_config() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Disabled agent test.").unwrap();
    fs::write(
        tmp.path().join(".imrule/imrule.toml"),
        "[agents.claude]\nenabled = false\n",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn apply_propagates_subagents_to_native_dirs() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule/agents")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Subagent test.").unwrap();
    fs::write(
        tmp.path().join(".imrule/agents/coder.md"),
        "---\nname: coder\ndescription: Helps with coding\n---\n\nCode assistant instructions.\n",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cursor,codex,copilot",
        ])
        .assert()
        .success();

    assert!(tmp.path().join(".claude/agents/coder.md").exists());
    assert!(tmp.path().join(".cursor/agents/coder.md").exists());
    assert!(tmp.path().join(".codex/agents/coder.md").exists());
    assert!(tmp.path().join(".github/agents/coder.md").exists());
}

#[test]
fn clear_removes_managed_skills_from_agent_dirs() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule/skills/my-skill")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Skills clear test.").unwrap();
    fs::write(
        tmp.path().join(".imrule/skills/my-skill/SKILL.md"),
        "# My skill",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    assert!(tmp.path().join(".claude/skills/my-skill/SKILL.md").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join(".claude/skills/my-skill").exists());
    assert!(tmp.path().join(".imrule/skills/my-skill").exists());
}

#[test]
fn clear_prunes_empty_parent_directories() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Prune dirs test.").unwrap();

    // Apply to agents that write into nested directories.
    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "antigravity,jetbrains-ai,amazonqcli",
        ])
        .assert()
        .success();

    // Verify nested dirs were created.
    assert!(tmp.path().join(".agent/rules/imrule.md").exists());
    assert!(tmp.path().join(".aiassistant/rules/AGENTS.md").exists());
    assert!(tmp.path().join(".amazonq/rules/imrule_q_rules.md").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "antigravity,jetbrains-ai,amazonqcli",
        ])
        .assert()
        .success();

    // Generated files removed.
    assert!(!tmp.path().join(".agent/rules/imrule.md").exists());
    assert!(!tmp.path().join(".aiassistant/rules/AGENTS.md").exists());
    assert!(!tmp.path().join(".amazonq/rules/imrule_q_rules.md").exists());

    // Empty parent directories must also be pruned.
    assert!(!tmp.path().join(".agent").exists());
    assert!(!tmp.path().join(".aiassistant").exists());
    assert!(!tmp.path().join(".amazonq").exists());
}

#[test]
fn clear_removes_entire_skills_directory() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule/skills/openai")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Skills dir clear.").unwrap();
    fs::write(
        tmp.path().join(".imrule/skills/openai/SKILL.md"),
        "# openai skill",
    )
    .unwrap();
    fs::write(
        tmp.path().join(".imrule/skills/openai/openai.yaml"),
        "name: openai",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,codex",
        ])
        .assert()
        .success();

    // Skills propagated to agent dirs.
    assert!(tmp.path().join(".claude/skills/openai/SKILL.md").exists());
    assert!(tmp
        .path()
        .join(".claude/skills/openai/openai.yaml")
        .exists());
    assert!(tmp.path().join(".codex/skills/openai/SKILL.md").exists());
    assert!(tmp.path().join(".codex/skills/openai/openai.yaml").exists());

    // Remove .imrule/skills so discover_skills won't find names.
    fs::remove_dir_all(tmp.path().join(".imrule/skills")).unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,codex",
        ])
        .assert()
        .success();

    // Skills directories must be fully removed even though .imrule/skills no longer exists.
    assert!(!tmp.path().join(".claude/skills").exists());
    assert!(!tmp.path().join(".codex/skills").exists());
    assert!(!tmp.path().join(".claude").exists());
    assert!(!tmp.path().join(".codex").exists());
}

#[test]
fn clear_removes_subagent_directories_and_prunes_parents() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule/agents")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Subagent clear test.").unwrap();
    fs::write(
        tmp.path().join(".imrule/agents/coder.md"),
        "---\nname: coder\ndescription: Helps with coding\n---\n\nCode assistant.\n",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cursor,codex,copilot",
        ])
        .assert()
        .success();

    // Subagents were propagated.
    assert!(tmp.path().join(".claude/agents/coder.md").exists());
    assert!(tmp.path().join(".cursor/agents/coder.md").exists());
    assert!(tmp.path().join(".codex/agents/coder.md").exists());
    assert!(tmp.path().join(".github/agents/coder.md").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cursor,codex,copilot",
        ])
        .assert()
        .success();

    // Subagent directories removed.
    assert!(!tmp.path().join(".claude/agents").exists());
    assert!(!tmp.path().join(".cursor/agents").exists());
    assert!(!tmp.path().join(".codex/agents").exists());
    assert!(!tmp.path().join(".github/agents").exists());

    // Empty parent directories pruned.
    assert!(!tmp.path().join(".claude").exists());
    assert!(!tmp.path().join(".cursor").exists());
    assert!(!tmp.path().join(".codex").exists());
    assert!(!tmp.path().join(".github").exists());
}

#[test]
fn clear_removes_empty_mcp_config_and_prunes_parents() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "MCP prune test.").unwrap();
    fs::write(
        tmp.path().join(".imrule/mcp.json"),
        r#"{"mcpServers":{"my-tool":{"command":"node"}}}"#,
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "cursor",
        ])
        .assert()
        .success();

    // Cursor MCP config was created.
    assert!(tmp.path().join(".cursor/mcp.json").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "cursor",
        ])
        .assert()
        .success();

    // MCP config file removed (was only imrule keys).
    assert!(!tmp.path().join(".cursor/mcp.json").exists());
    // Empty .cursor directory pruned.
    assert!(!tmp.path().join(".cursor").exists());
}

#[test]
fn clear_removes_imrule_mcp_keys_from_native_config() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::create_dir_all(tmp.path().join(".cursor")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "MCP clear test.").unwrap();
    fs::write(
        tmp.path().join(".imrule/mcp.json"),
        r#"{"mcpServers":{"imrule-tool":{"command":"node"}}}"#,
    )
    .unwrap();
    fs::write(
        tmp.path().join(".cursor/mcp.json"),
        r#"{"mcpServers":{"other-tool":{"command":"python"}}}"#,
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "cursor",
        ])
        .assert()
        .success();

    let after_apply: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(tmp.path().join(".cursor/mcp.json")).unwrap())
            .unwrap();
    assert!(after_apply["mcpServers"]["imrule-tool"].is_object());
    assert!(after_apply["mcpServers"]["other-tool"].is_object());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "cursor",
        ])
        .assert()
        .success();

    let after_clear: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(tmp.path().join(".cursor/mcp.json")).unwrap())
            .unwrap();
    assert!(after_clear["mcpServers"].get("imrule-tool").is_none());
    assert!(after_clear["mcpServers"]["other-tool"].is_object());
}

#[test]
fn skills_list_shows_installed_skills() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule/skills/my-skill")).unwrap();
    fs::write(
        tmp.path().join(".imrule/skills/my-skill/SKILL.md"),
        "# My skill",
    )
    .unwrap();

    let output = Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "skills",
            "list",
            "--project-root",
            tmp.path().to_str().unwrap(),
        ])
        .output()
        .unwrap();
    assert!(output.status.success());
    let stdout = String::from_utf8_lossy(&output.stdout);
    assert!(stdout.contains("my-skill"));
}

#[test]
fn apply_errors_on_unknown_agent() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Error test.").unwrap();

    let output = Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "nonexistent-agent",
        ])
        .output()
        .unwrap();
    assert!(!output.status.success());
}

#[test]
fn apply_uses_global_imrule_dir_as_fallback() {
    let xdg_home = tempdir().unwrap();
    let project = tempdir().unwrap();

    fs::create_dir_all(xdg_home.path().join("imrule")).unwrap();
    fs::write(
        xdg_home.path().join("imrule/AGENTS.md"),
        "Global fallback rules.",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .env("XDG_CONFIG_HOME", xdg_home.path())
        .args([
            "apply",
            "--project-root",
            project.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    let claude = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();
    assert!(claude.contains("Global fallback rules."));
}

#[test]
fn clear_removes_custom_output_path_from_config() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(
        tmp.path().join(".imrule/AGENTS.md"),
        "Custom output path clear test.",
    )
    .unwrap();
    fs::write(
        tmp.path().join(".imrule/imrule.toml"),
        "[agents.claude]\noutput_path = \"rules/MY_CLAUDE.md\"\n",
    )
    .unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    // Custom output path was used, not default CLAUDE.md.
    assert!(!tmp.path().join("CLAUDE.md").exists());
    assert!(tmp.path().join("rules/MY_CLAUDE.md").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "clear",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    // Custom output path file removed.
    assert!(!tmp.path().join("rules/MY_CLAUDE.md").exists());
    // Empty parent directories pruned.
    assert!(!tmp.path().join("rules").exists());
}

#[test]
fn mcp_add_and_remove_persist_to_imrule_toml() {
    let tmp = tempdir().unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .assert()
        .success();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "mcp",
            "add",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--transport",
            "http",
            "linear",
            "https://mcp.linear.app/mcp",
        ])
        .assert()
        .success();

    let toml = fs::read_to_string(tmp.path().join(".imrule/imrule.toml")).unwrap();
    assert!(toml.contains("[mcp_servers.linear]"));
    assert!(toml.contains("transport = \"http\""));
    assert!(toml.contains("url = \"https://mcp.linear.app/mcp\""));

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "mcp",
            "add",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "-e",
            "GITHUB_TOKEN=xxx",
            "github",
            "--",
            "npx",
            "-y",
            "@modelcontextprotocol/server-github",
        ])
        .assert()
        .success();

    let toml = fs::read_to_string(tmp.path().join(".imrule/imrule.toml")).unwrap();
    assert!(toml.contains("[mcp_servers.github]"));
    assert!(toml.contains("command = \"npx\""));
    assert!(toml.contains("GITHUB_TOKEN = \"xxx\""));

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    let claude_mcp: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(tmp.path().join(".mcp.json")).unwrap()).unwrap();
    assert_eq!(
        claude_mcp["mcpServers"]["linear"]["type"],
        serde_json::json!("http")
    );
    assert_eq!(
        claude_mcp["mcpServers"]["linear"]["url"],
        serde_json::json!("https://mcp.linear.app/mcp")
    );
    assert_eq!(
        claude_mcp["mcpServers"]["github"]["type"],
        serde_json::json!("stdio")
    );
    assert_eq!(
        claude_mcp["mcpServers"]["github"]["command"],
        serde_json::json!("npx")
    );

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "mcp",
            "remove",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "linear",
        ])
        .assert()
        .success();

    let toml = fs::read_to_string(tmp.path().join(".imrule/imrule.toml")).unwrap();
    assert!(!toml.contains("[mcp_servers.linear]"));
}

#[test]
fn mcp_remove_missing_server_fails() {
    let tmp = tempdir().unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .assert()
        .success();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "mcp",
            "remove",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "missing",
        ])
        .assert()
        .failure();
}
