use std::fs;

use assert_cmd::Command;
use tempfile::tempdir;

#[test]
fn cli_version_and_help_are_release_ready() {
    let version = Command::cargo_bin("imrule")
        .unwrap()
        .arg("--version")
        .output()
        .unwrap();
    assert!(version.status.success());
    assert!(String::from_utf8_lossy(&version.stdout).contains("imrule 0.4.0"));

    let help = Command::cargo_bin("imrule")
        .unwrap()
        .arg("apply")
        .arg("--help")
        .output()
        .unwrap();
    assert!(help.status.success());
    let stdout = String::from_utf8_lossy(&help.stdout);
    assert!(stdout.contains("Apply imrule configurations to supported AI agents"));
    assert!(stdout.contains("--project-root"));
    assert!(stdout.contains("--no-mcp"));
    assert!(stdout.contains("agentsmd, aider, amazonqcli"));
}

#[test]
fn apply_and_revert_are_native_rust_commands() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Always be concise.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
            "--no-mcp",
        ])
        .assert()
        .success();

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.starts_with("<!-- Generated by ImRule -->"));
    assert!(claude.contains("Always be concise."));
    assert!(tmp.path().join(".clinerules").is_file());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "revert",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude,cline",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
    assert!(!tmp.path().join(".clinerules").exists());
}

#[test]
fn apply_dry_run_does_not_write_outputs() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "Dry run only.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--no-mcp",
            "--dry-run",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn init_scaffolds_imrule_files_without_overwriting_existing_content() {
    let tmp = tempdir().unwrap();

    let init = Command::cargo_bin("imrule")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .output()
        .unwrap();
    assert!(init.status.success());
    assert!(String::from_utf8_lossy(&init.stdout).contains("ImRule initialized"));

    let agents = tmp.path().join(".imrule/AGENTS.md");
    let toml = tmp.path().join(".imrule/imrule.toml");
    assert!(fs::read_to_string(&agents)
        .unwrap()
        .contains("Centralised AI agent instructions"));
    assert!(fs::read_to_string(&toml)
        .unwrap()
        .contains("default_agents"));

    fs::write(&agents, "custom").unwrap();
    Command::cargo_bin("imrule")
        .unwrap()
        .args(["init", "--project-root", tmp.path().to_str().unwrap()])
        .assert()
        .success();
    assert_eq!(fs::read_to_string(&agents).unwrap(), "custom");
}

#[test]
fn init_global_uses_xdg_config_home() {
    let tmp = tempdir().unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .env("XDG_CONFIG_HOME", tmp.path())
        .args(["init", "--global"])
        .assert()
        .success();

    assert!(tmp.path().join("imrule/AGENTS.md").is_file());
    assert!(tmp.path().join("imrule/imrule.toml").is_file());
}

#[test]
fn apply_works_with_legacy_ruler_directory() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Legacy ruler rules.").unwrap();

    let output = Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--no-mcp",
        ])
        .output()
        .unwrap();
    assert!(output.status.success());

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.starts_with("<!-- Generated by ImRule -->"));
    assert!(claude.contains("Legacy ruler rules."));

    // Should print deprecation warning to stderr.
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("legacy '.ruler/' directory"));
}

#[test]
fn revert_works_with_legacy_ruler_directory() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Legacy ruler rules.").unwrap();

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--no-mcp",
        ])
        .assert()
        .success();

    assert!(tmp.path().join("CLAUDE.md").exists());

    Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "revert",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
        ])
        .assert()
        .success();

    assert!(!tmp.path().join("CLAUDE.md").exists());
}

#[test]
fn apply_prefers_imrule_over_ruler_when_both_exist() {
    let tmp = tempdir().unwrap();
    fs::create_dir_all(tmp.path().join(".imrule")).unwrap();
    fs::create_dir_all(tmp.path().join(".ruler")).unwrap();
    fs::write(tmp.path().join(".imrule/AGENTS.md"), "New rules.").unwrap();
    fs::write(tmp.path().join(".ruler/AGENTS.md"), "Old rules.").unwrap();

    let output = Command::cargo_bin("imrule")
        .unwrap()
        .args([
            "apply",
            "--project-root",
            tmp.path().to_str().unwrap(),
            "--agents",
            "claude",
            "--no-mcp",
        ])
        .output()
        .unwrap();
    assert!(output.status.success());

    let claude = fs::read_to_string(tmp.path().join("CLAUDE.md")).unwrap();
    assert!(claude.contains("New rules."));
    assert!(!claude.contains("Old rules."));

    // No deprecation warning when .imrule exists.
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(!stderr.contains("legacy"));
}
