use std::fs;
use std::path::PathBuf;

use imrule::application::ports::{ConfigPort, FileSystemPort, GitignorePort};
use imrule::domain::config::McpStrategy;
use imrule::domain::rules::concatenate_rules;
use imrule::infrastructure::config_loader::TomlConfigLoader;
use imrule::infrastructure::file_system::FsFileSystem;
use imrule::infrastructure::gitignore::GitignoreUpdater;
use tempfile::tempdir;

#[test]
fn concatenate_rules_matches_native_section_format() {
    let tmp = tempdir().unwrap();
    let base = tmp.path();
    let files = vec![
        (
            base.join(".imrule/AGENTS.md"),
            "\n# Root Rules\n\nPrimary rule.\n\n".to_string(),
        ),
        (
            base.join(".imrule/nested/extra.md"),
            "# Extra Rules\n\nSecondary rule.\n".to_string(),
        ),
    ];

    let actual = concatenate_rules(&files, Some(base));

    assert_eq!(
        actual,
        "\n\n<!-- Source: .imrule/AGENTS.md -->\n\n# Root Rules\n\nPrimary rule.\n\n\n\n<!-- Source: .imrule/nested/extra.md -->\n\n# Extra Rules\n\nSecondary rule.\n"
    );
}

#[test]
fn read_markdown_files_orders_primary_skips_skills_and_agents_by_default() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    let imrule_dir = root.join(".imrule");
    fs::create_dir_all(imrule_dir.join("skills/demo")).unwrap();
    fs::create_dir_all(imrule_dir.join("agents")).unwrap();
    fs::create_dir_all(imrule_dir.join("z")).unwrap();
    fs::write(imrule_dir.join("z/last.md"), "last").unwrap();
    fs::write(imrule_dir.join("AGENTS.md"), "primary").unwrap();
    fs::write(imrule_dir.join("alpha.md"), "alpha").unwrap();
    fs::write(imrule_dir.join("skills/demo/SKILL.md"), "skill").unwrap();
    fs::write(imrule_dir.join("agents/helper.md"), "agent").unwrap();
    fs::write(
        root.join("AGENTS.md"),
        "<!-- Generated by ImRule -->\n\n<!-- Source: .imrule/AGENTS.md -->\nold",
    )
    .unwrap();

    let fs = FsFileSystem::new();
    let files = fs.read_markdown_files(&imrule_dir, false).unwrap();
    let rels: Vec<_> = files
        .iter()
        .map(|(path, _)| {
            path.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    assert_eq!(
        rels,
        vec![".imrule/AGENTS.md", ".imrule/alpha.md", ".imrule/z/last.md"]
    );
}

#[test]
fn read_markdown_files_can_include_agents_and_root_agents_when_not_generated() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    let imrule_dir = root.join(".imrule");
    fs::create_dir_all(imrule_dir.join("agents")).unwrap();
    fs::write(root.join("AGENTS.md"), "human root").unwrap();
    fs::write(imrule_dir.join("instructions.md"), "legacy primary").unwrap();
    fs::write(imrule_dir.join("agents/helper.md"), "agent").unwrap();

    let fs = FsFileSystem::new();
    let files = fs.read_markdown_files(&imrule_dir, true).unwrap();
    let rels: Vec<_> = files
        .iter()
        .map(|(path, _)| {
            path.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    assert_eq!(
        rels,
        vec![
            "AGENTS.md",
            ".imrule/instructions.md",
            ".imrule/agents/helper.md"
        ]
    );
}

#[test]
fn update_gitignore_replaces_managed_block_and_filters_existing_and_imrule_inputs() {
    let tmp = tempdir().unwrap();
    let root = tmp.path().join("imrule");
    fs::create_dir_all(&root).unwrap();
    fs::write(
        root.join(".gitignore"),
        "node_modules\n# START ImRule Generated Files\n/old.md\n# END ImRule Generated Files\n/dist\n",
    )
    .unwrap();

    let gitignore = GitignoreUpdater::new();
    gitignore
        .update_gitignore(
            &root,
            &[
                root.join("AGENTS.md"),
                PathBuf::from(".imrule/AIDER_RULES.md"),
                PathBuf::from(".imrule/AGENTS.md"),
                PathBuf::from("dist"),
                PathBuf::from("AGENTS.md"),
            ],
            ".gitignore",
        )
        .unwrap();

    assert_eq!(
        fs::read_to_string(root.join(".gitignore")).unwrap(),
        "node_modules\n# START ImRule Generated Files\n/AGENTS.md\n# END ImRule Generated Files\n/dist\n"
    );
}

#[test]
fn load_config_maps_toml_sections_and_resolves_output_paths() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".imrule")).unwrap();
    fs::write(
        root.join(".imrule/imrule.toml"),
        r#"
default_agents = ["agentsmd", "aider"]
nested = true

[mcp]
enabled = false
merge_strategy = "overwrite"

[gitignore]
enabled = true
local = true

[skills]
enabled = false

[agents]
enabled = true
include_in_rules = true

[agents.aider]
enabled = false
output_path = "rules/AIDER_RULES.md"
output_path_config = ".aider.conf.yml"

[agents.aider.mcp]
enabled = true
merge_strategy = "merge"
        "#,
    )
    .unwrap();

    let loader = TomlConfigLoader::new();
    let loaded = loader
        .load_config(root, None, Some(vec!["aider".to_string()]))
        .unwrap();

    assert_eq!(loaded.default_agents.unwrap(), vec!["agentsmd", "aider"]);
    assert_eq!(loaded.cli_agents.unwrap(), vec!["aider"]);
    assert!(loaded.nested);
    assert!(loaded.nested_defined);
    assert_eq!(loaded.mcp.unwrap().strategy, McpStrategy::Overwrite);
    assert_eq!(loaded.gitignore.unwrap().local, Some(true));
    assert_eq!(loaded.skills.unwrap().enabled, Some(false));
    assert_eq!(loaded.subagents.unwrap().include_in_rules, Some(true));

    let aider = loaded.agent_configs.get("aider").unwrap();
    assert_eq!(aider.enabled, Some(false));
    assert_eq!(
        aider.output_path.as_ref().unwrap(),
        &root.join("rules/AIDER_RULES.md")
    );
    assert_eq!(
        aider.output_path_config.as_ref().unwrap(),
        &root.join(".aider.conf.yml")
    );
    assert_eq!(aider.mcp.as_ref().unwrap().enabled, Some(true));
    assert_eq!(aider.mcp.as_ref().unwrap().strategy, McpStrategy::Merge);
}

#[test]
fn load_config_without_file_returns_empty_native_sections() {
    let tmp = tempdir().unwrap();

    let loader = TomlConfigLoader::new();
    let loaded = loader.load_config(tmp.path(), None, None).unwrap();

    assert!(loaded.default_agents.is_none());
    assert!(loaded.agent_configs.is_empty());
    let mcp = loaded.mcp.unwrap();
    assert_eq!(mcp.enabled, None);
    assert_eq!(mcp.strategy, McpStrategy::Merge);
    assert_eq!(loaded.gitignore.unwrap().enabled, None);
    assert_eq!(loaded.skills.unwrap().enabled, None);
    assert_eq!(loaded.subagents.unwrap().enabled, None);
    assert!(!loaded.nested);
    assert!(!loaded.nested_defined);
}

#[test]
fn write_generated_file_creates_parent_directories() {
    let tmp = tempdir().unwrap();
    let target = tmp.path().join("nested/out/AGENTS.md");

    let fs = FsFileSystem::new();
    fs.write_text(&target, "generated").unwrap();

    assert_eq!(fs::read_to_string(target).unwrap(), "generated");
}

// --- Legacy .ruler/ fallback tests ---

#[test]
fn find_imrule_dir_falls_back_to_ruler_dir() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".ruler")).unwrap();
    fs::write(root.join(".ruler/AGENTS.md"), "legacy rules").unwrap();

    let fs = FsFileSystem::new();
    let found = fs.find_imrule_dir(root, false);
    assert_eq!(found, Some(root.join(".ruler")));
}

#[test]
fn find_imrule_dir_prefers_imrule_over_ruler() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".imrule")).unwrap();
    fs::create_dir_all(root.join(".ruler")).unwrap();

    let fs = FsFileSystem::new();
    let found = fs.find_imrule_dir(root, false);
    assert_eq!(found, Some(root.join(".imrule")));
}

#[test]
fn read_markdown_files_works_with_ruler_dir() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    let ruler_dir = root.join(".ruler");
    fs::create_dir_all(&ruler_dir).unwrap();
    fs::write(ruler_dir.join("AGENTS.md"), "legacy primary").unwrap();
    fs::write(ruler_dir.join("extra.md"), "legacy extra").unwrap();

    let fs = FsFileSystem::new();
    let files = fs.read_markdown_files(&ruler_dir, false).unwrap();
    let rels: Vec<_> = files
        .iter()
        .map(|(path, _)| {
            path.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    assert_eq!(rels, vec![".ruler/AGENTS.md", ".ruler/extra.md"]);
}

#[test]
fn load_config_falls_back_to_ruler_toml() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".ruler")).unwrap();
    fs::write(
        root.join(".ruler/ruler.toml"),
        r#"
default_agents = ["claude"]

[mcp]
enabled = false
"#,
    )
    .unwrap();

    let loader = TomlConfigLoader::new();
    let loaded = loader.load_config(root, None, None).unwrap();
    assert_eq!(loaded.default_agents.unwrap(), vec!["claude"]);
    assert_eq!(loaded.mcp.unwrap().enabled, Some(false));
}

#[test]
fn load_config_falls_back_to_ruler_dir_with_imrule_toml() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".ruler")).unwrap();
    fs::write(
        root.join(".ruler/imrule.toml"),
        r#"
default_agents = ["copilot"]
"#,
    )
    .unwrap();

    let loader = TomlConfigLoader::new();
    let loaded = loader.load_config(root, None, None).unwrap();
    assert_eq!(loaded.default_agents.unwrap(), vec!["copilot"]);
}

#[test]
fn load_config_prefers_imrule_toml_over_ruler_toml() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".imrule")).unwrap();
    fs::create_dir_all(root.join(".ruler")).unwrap();
    fs::write(
        root.join(".imrule/imrule.toml"),
        r#"default_agents = ["claude"]"#,
    )
    .unwrap();
    fs::write(
        root.join(".ruler/ruler.toml"),
        r#"default_agents = ["copilot"]"#,
    )
    .unwrap();

    let loader = TomlConfigLoader::new();
    let loaded = loader.load_config(root, None, None).unwrap();
    assert_eq!(loaded.default_agents.unwrap(), vec!["claude"]);
}

#[test]
fn load_config_walks_up_parent_dirs() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    let subdir = root.join("sub/nested");
    fs::create_dir_all(root.join(".imrule")).unwrap();
    fs::create_dir_all(&subdir).unwrap();
    fs::write(
        root.join(".imrule/imrule.toml"),
        r#"default_agents = ["codex", "claude", "kilocode"]"#,
    )
    .unwrap();

    let loader = TomlConfigLoader::new();
    // Load config starting from a subdirectory — should walk up and find root's config.
    let loaded = loader.load_config(&subdir, None, None).unwrap();
    assert_eq!(
        loaded.default_agents.unwrap(),
        vec!["codex", "claude", "kilocode"]
    );
}

#[test]
fn update_gitignore_filters_ruler_input_paths() {
    let tmp = tempdir().unwrap();
    let root = tmp.path().join("proj");
    fs::create_dir_all(&root).unwrap();
    fs::write(root.join(".gitignore"), "").unwrap();

    let gitignore = GitignoreUpdater::new();
    gitignore
        .update_gitignore(
            &root,
            &[
                PathBuf::from(".ruler/AGENTS.md"),
                PathBuf::from(".ruler/rules.md"),
                PathBuf::from("CLAUDE.md"),
            ],
            ".gitignore",
        )
        .unwrap();

    let content = fs::read_to_string(root.join(".gitignore")).unwrap();
    assert!(!content.contains(".ruler/"));
    assert!(content.contains("/CLAUDE.md"));
}

#[test]
fn find_all_imrule_dirs_discovers_ruler_dirs() {
    let tmp = tempdir().unwrap();
    let root = tmp.path();
    fs::create_dir_all(root.join(".ruler")).unwrap();
    fs::create_dir_all(root.join("subdir/.imrule")).unwrap();

    let fs = FsFileSystem::new();
    let found = fs.find_all_imrule_dirs(root);
    let rels: Vec<_> = found
        .iter()
        .map(|p| {
            p.strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/")
        })
        .collect();

    assert!(rels.contains(&".ruler".to_string()));
    assert!(rels.contains(&"subdir/.imrule".to_string()));
}
