//! CLI argument definitions using clap.

use std::path::PathBuf;

use clap::{ArgAction, Args, Parser, Subcommand};

const AGENT_IDENTIFIERS: &str = "agentsmd, aider, amazonqcli, amp, antigravity, augmentcode, claude, cline, codex, copilot, crush, cursor, factory, firebase, firebender, gemini-cli, goose, jetbrains-ai, jules, junie, kilocode, kiro, mistral, opencode, openhands, pi, qwen, roo, trae, warp, windsurf, zed";

#[derive(Debug, Parser)]
#[command(name = "imrule")]
#[command(version)]
#[command(about = "ImRule — apply the same rules to all coding agents")]
#[command(override_usage = "imrule <command> [options]")]
#[command(subcommand_required = true, arg_required_else_help = true)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Command,
}

#[derive(Debug, Subcommand)]
pub enum Command {
    /// Apply imrule configurations to supported AI agents.
    Apply(ApplyArgs),
    /// Remove all assets generated by imrule apply.
    Clear(ClearArgs),
    /// Scaffold a .imrule directory with default files.
    Init(InitArgs),
    /// Revert imrule configurations from supported AI agents.
    Revert(RevertArgs),
    /// Manage agent skills.
    Skills(SkillsArgs),
}

#[derive(Debug, Subcommand)]
pub enum SkillsCommand {
    /// Install skills from a remote repository or local path.
    Add(SkillsAddArgs),
    /// List installed skills.
    #[command(alias = "ls")]
    List(SkillsListArgs),
}

#[derive(Debug, Args)]
pub struct SkillsArgs {
    #[command(subcommand)]
    pub command: SkillsCommand,
}

#[derive(Debug, Args)]
pub struct SkillsAddArgs {
    /// Skill source: org/repo, GitHub URL, GitLab URL, git SSH URL, or local path.
    pub source: String,
    /// Install specific skills by name (use '*' for all).
    #[arg(long, short = 's', value_name = "NAME")]
    pub skill: Option<Vec<String>>,
    /// List available skills without installing.
    #[arg(long, short = 'l', default_value_t = false)]
    pub list: bool,
    /// Install to global config directory instead of project.
    #[arg(long, short = 'g', default_value_t = false)]
    pub global: bool,
    /// Project root directory.
    #[arg(long = "project-root", value_name = "DIR")]
    pub project_root: Option<PathBuf>,
    /// Enable verbose logging.
    #[arg(long, short = 'v', default_value_t = false)]
    pub verbose: bool,
}

#[derive(Debug, Args)]
pub struct SkillsListArgs {
    /// List global skills instead of project skills.
    #[arg(long, short = 'g', default_value_t = false)]
    pub global: bool,
    /// Project root directory.
    #[arg(long = "project-root", value_name = "DIR")]
    pub project_root: Option<PathBuf>,
}

#[derive(Debug, Args)]
#[command(after_help = AGENT_IDENTIFIERS)]
pub struct ApplyArgs {
    /// Project root directory.
    #[arg(long = "project-root", value_name = "DIR")]
    pub project_root: Option<PathBuf>,
    /// Comma-separated list of agent identifiers.
    #[arg(long, value_name = "IDS")]
    pub agents: Option<String>,
    /// Path to TOML configuration file.
    #[arg(long, value_name = "FILE")]
    pub config: Option<PathBuf>,
    /// Enable verbose logging.
    #[arg(long, short = 'v', default_value_t = false)]
    pub verbose: bool,
    /// Preview changes without writing files.
    #[arg(long = "dry-run", default_value_t = false)]
    pub dry_run: bool,
    /// Create .bak backup files before overwriting.
    #[arg(long, action = ArgAction::SetTrue)]
    pub backup: bool,
}

#[derive(Debug, Args)]
pub struct InitArgs {
    /// Project root directory.
    #[arg(long = "project-root", value_name = "DIR")]
    pub project_root: Option<PathBuf>,
    /// Initialize in global config directory (XDG_CONFIG_HOME/imrule).
    #[arg(long = "global", default_value_t = false)]
    pub global: bool,
}

#[derive(Debug, Args)]
#[command(after_help = AGENT_IDENTIFIERS)]
pub struct RevertArgs {
    /// Project root directory.
    #[arg(long = "project-root", value_name = "DIR")]
    pub project_root: Option<PathBuf>,
    /// Comma-separated list of agent identifiers.
    #[arg(long, value_name = "IDS")]
    pub agents: Option<String>,
    /// Path to TOML configuration file.
    #[arg(long, value_name = "FILE")]
    pub config: Option<PathBuf>,
    /// Enable verbose logging.
    #[arg(long, short = 'v', default_value_t = false)]
    pub verbose: bool,
    /// Preview changes without writing files.
    #[arg(long = "dry-run", default_value_t = false)]
    pub dry_run: bool,
}

#[derive(Debug, Args)]
#[command(after_help = AGENT_IDENTIFIERS)]
pub struct ClearArgs {
    /// Project root directory.
    #[arg(long = "project-root", value_name = "DIR")]
    pub project_root: Option<PathBuf>,
    /// Comma-separated list of agent identifiers.
    #[arg(long, value_name = "IDS")]
    pub agents: Option<String>,
    /// Path to TOML configuration file.
    #[arg(long, value_name = "FILE")]
    pub config: Option<PathBuf>,
    /// Preview changes without removing files.
    #[arg(long = "dry-run", default_value_t = false)]
    pub dry_run: bool,
    /// Also remove the .imrule/ source directory.
    #[arg(long = "remove-source", default_value_t = false)]
    pub remove_source: bool,
    /// Enable verbose logging.
    #[arg(long, short = 'v', default_value_t = false)]
    pub verbose: bool,
}

pub fn parse_agents(agents: Option<String>) -> Option<Vec<String>> {
    agents.map(|value| {
        value
            .split(',')
            .map(str::trim)
            .filter(|item| !item.is_empty())
            .map(ToOwned::to_owned)
            .collect()
    })
}
