#!/usr/bin/env python3
"""Regenerates src/domain/shipped_skills.rs from the release tags.

`imrule skills setup` refreshes a built-in skill installed from an older
revision only when that copy is exactly what a release shipped; anything else
counts as edited locally. This script records, for every release tag, each
built-in skill's path, revision and per-file FNV-1a digest.

Run it after tagging a release that changed a built-in skill (`make
shipped-skills`), and commit the result.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/domain/shipped_skills.rs"
# Built-in skills first shipped in 0.5.0.0.
FIRST_TAG = (0, 5, 0, 0)
REVISION_RE = re.compile(r'^\s+imrule-skill-version:\s*"?(\d+)"?\s*$', re.M)


def git(*args: str) -> bytes:
    return subprocess.run(["git", *args], cwd=ROOT, check=True, capture_output=True).stdout


def release_tags() -> list[str]:
    tags = []
    for tag in git("tag", "--list", "v*").decode().split():
        parts = tag[1:].split(".")
        if len(parts) == 4 and all(part.isdigit() for part in parts):
            if tuple(int(part) for part in parts) >= FIRST_TAG:
                tags.append(tag)
    return sorted(tags, key=lambda tag: tuple(int(part) for part in tag[1:].split(".")))


def fnv1a(data: bytes) -> int:
    digest = 0xCBF29CE484222325
    for byte in data:
        digest ^= byte
        digest = (digest * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return digest


def embedded(relative: str) -> bool:
    """Mirrors build.rs: hidden entries and `__pycache__` are not embedded."""
    return not any(part.startswith(".") or part == "__pycache__" for part in relative.split("/"))


def shipped_at(tag: str) -> dict[tuple[str, int], tuple[tuple[str, int], ...]]:
    files = [
        name[len("skills/"):]
        for name in git("ls-tree", "-r", "--name-only", tag, "--", "skills").decode().splitlines()
    ]
    skills = sorted(name[: -len("/SKILL.md")] for name in files if name.endswith("/SKILL.md"))
    shipped = {}
    for skill in skills:
        skill_md = git("show", f"{tag}:skills/{skill}/SKILL.md").decode()
        match = REVISION_RE.search(skill_md)
        if not match:
            sys.exit(f"{tag}: skills/{skill}/SKILL.md has no imrule-skill-version")
        digests = tuple(
            sorted(
                (name[len(skill) + 1:], fnv1a(git("show", f"{tag}:skills/{name}")))
                for name in files
                if name.startswith(f"{skill}/") and embedded(name[len(skill) + 1:])
            )
        )
        shipped[(skill, int(match.group(1)))] = digests
    return shipped


def main() -> None:
    entries: dict[tuple[str, int, tuple[tuple[str, int], ...]], list[str]] = {}
    for tag in release_tags():
        for (path, revision), files in shipped_at(tag).items():
            entries.setdefault((path, revision, files), []).append(tag)

    lines = [
        "// @generated by scripts/shipped-skills.py from the release tags; do not edit.",
        "//! Every built-in skill revision a release installed: where, and each",
        "//! file's [`content_digest`](super::builtin_skills::content_digest).",
        "",
        "use super::builtin_skills::ShippedRevision;",
        "",
        "pub const SHIPPED_BUILTIN_REVISIONS: &[ShippedRevision] = &[",
    ]
    for (path, revision, files), tags in sorted(entries.items(), key=lambda item: item[0][:2]):
        lines.append(f"    // {', '.join(tags)}")
        lines.append("    ShippedRevision {")
        lines.append(f"        path: {path!r},".replace("'", '"'))
        lines.append(f"        revision: {revision},")
        lines.append("        files: &[")
        for relative, digest in files:
            lines.append(f'            ("{relative}", 0x{digest:016x}),')
        lines.append("        ],")
        lines.append("    },")
    lines.append("];")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    subprocess.run(["rustfmt", "--edition", "2024", str(OUTPUT)], cwd=ROOT, check=True)
    print(f"wrote {len(entries)} shipped revisions to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
