#!/usr/bin/env bash
# End-to-end tests for init/apply/clear against the release binary.
# Run through `make test-e2e`, which builds the binary first.
set -euo pipefail

source "$(dirname "$0")/e2e-lib.sh"

TEST_DIR="${TEST_DIR:-test-e2e}"

echo ""; echo "━━━ E2E: imrule init (local) ━━━"
reset_dir init-local
"$BINARY" init --project-root "$TMP/init-local"
assert ".imrule directory created" test -d "$TMP/init-local/.imrule"
assert "imrule.toml created" test -f "$TMP/init-local/.imrule/imrule.toml"
assert "AGENTS.md created" test -f "$TMP/init-local/.imrule/AGENTS.md"

echo ""; echo "━━━ E2E: imrule init --global ━━━"
reset_dir init-global
XDG_CONFIG_HOME="$TMP/init-global" "$BINARY" init --global
assert "global dir created" test -d "$TMP/init-global/imrule"
assert "global imrule.toml created" test -f "$TMP/init-global/imrule/imrule.toml"
assert "global AGENTS.md created" test -f "$TMP/init-global/imrule/AGENTS.md"

echo ""; echo "━━━ E2E: imrule init (idempotent) ━━━"
"$BINARY" init --project-root "$TMP/init-local"
assert "init did not overwrite existing files" grep -q "ImRule Configuration File" "$TMP/init-local/.imrule/imrule.toml"

echo ""; echo "━━━ E2E: imrule apply (all agents) ━━━"
fresh_fixture apply-all
"$BINARY" apply --project-root "$TMP/apply-all" --verbose
assert "CLAUDE.md generated" test -f "$TMP/apply-all/CLAUDE.md"
assert "copilot instructions generated" test -f "$TMP/apply-all/.github/copilot-instructions.md"
assert "CLAUDE.md has marker" grep -q "Generated by ImRule" "$TMP/apply-all/CLAUDE.md"
assert "CLAUDE.md has source comment" grep -q "Source:" "$TMP/apply-all/CLAUDE.md"

echo ""; echo "━━━ E2E: imrule apply --dry-run ━━━"
fresh_fixture apply-dryrun
"$BINARY" apply --project-root "$TMP/apply-dryrun" --dry-run --verbose
assert_not "dry-run did not write files" test -f "$TMP/apply-dryrun/CLAUDE.md"

echo ""; echo "━━━ E2E: imrule apply --agents claude ━━━"
fresh_fixture apply-single
"$BINARY" apply --project-root "$TMP/apply-single" --agents claude --verbose
assert "CLAUDE.md generated" test -f "$TMP/apply-single/CLAUDE.md"
assert_not "copilot not generated" test -f "$TMP/apply-single/.github/copilot-instructions.md"

echo ""; echo "━━━ E2E: imrule apply --agents claude,copilot ━━━"
fresh_fixture apply-multi
"$BINARY" apply --project-root "$TMP/apply-multi" --agents claude,copilot --verbose
assert "CLAUDE.md generated" test -f "$TMP/apply-multi/CLAUDE.md"
assert "copilot instructions generated" test -f "$TMP/apply-multi/.github/copilot-instructions.md"

echo ""; echo "━━━ E2E: imrule apply (no MCP config present) ━━━"
fresh_fixture apply-nomcp
"$BINARY" apply --project-root "$TMP/apply-nomcp" --agents claude --verbose
assert "CLAUDE.md generated" test -f "$TMP/apply-nomcp/CLAUDE.md"

echo ""; echo "━━━ E2E: imrule apply (MCP merge) ━━━"
fresh_fixture apply-mcp
cp "$TEST_DIR/claude_desktop_config.json" "$TMP/apply-mcp/claude_desktop_config.json" 2>/dev/null || true
"$BINARY" apply --project-root "$TMP/apply-mcp" --agents claude --verbose
assert "CLAUDE.md generated" test -f "$TMP/apply-mcp/CLAUDE.md"

echo ""; echo "━━━ E2E: imrule apply --backup (creates .bak) ━━━"
fresh_fixture apply-backup
printf "# original\n" > "$TMP/apply-backup/CLAUDE.md"
"$BINARY" apply --project-root "$TMP/apply-backup" --agents claude --backup
assert ".bak created" test -f "$TMP/apply-backup/CLAUDE.md.bak"
assert ".bak has original content" grep -q "original" "$TMP/apply-backup/CLAUDE.md.bak"

echo ""; echo "━━━ E2E: imrule apply (no --backup, no .bak) ━━━"
fresh_fixture apply-nobak
printf "# original\n" > "$TMP/apply-nobak/CLAUDE.md"
"$BINARY" apply --project-root "$TMP/apply-nobak" --agents claude
assert_not "no .bak created" test -f "$TMP/apply-nobak/CLAUDE.md.bak"

echo ""; echo "━━━ E2E: imrule apply (gitignore) ━━━"
fresh_fixture apply-gitignore
touch "$TMP/apply-gitignore/.gitignore"
"$BINARY" apply --project-root "$TMP/apply-gitignore" --agents claude --verbose
assert ".gitignore updated" grep -q "ImRule Generated Files" "$TMP/apply-gitignore/.gitignore"

echo ""; echo "━━━ E2E: imrule clear (basic) ━━━"
fresh_fixture clear-basic
"$BINARY" apply --project-root "$TMP/clear-basic" --agents claude
assert "CLAUDE.md exists" test -f "$TMP/clear-basic/CLAUDE.md"
"$BINARY" clear --project-root "$TMP/clear-basic" --agents claude
assert_not "CLAUDE.md removed" test -f "$TMP/clear-basic/CLAUDE.md"

echo ""; echo "━━━ E2E: imrule clear --dry-run ━━━"
fresh_fixture clear-dryrun
"$BINARY" apply --project-root "$TMP/clear-dryrun" --agents claude
"$BINARY" clear --project-root "$TMP/clear-dryrun" --agents claude --dry-run
assert "file not removed on dry-run" test -f "$TMP/clear-dryrun/CLAUDE.md"

echo ""; echo "━━━ E2E: error on unknown agent ━━━"
fresh_fixture err-agent
assert_not "error on unknown agent" "$BINARY" apply --project-root "$TMP/err-agent" --agents nonexistent 2>/dev/null

echo ""; echo "━━━ E2E: all tests passed ━━━"
