//! Clear use case — removes all imrule-generated assets.

use std::path::{Path, PathBuf};

use rayon::prelude::*;

use crate::application::apply_use_case::{instruction_output_path, resolve_selected_agents};
use crate::application::ports::{ConfigPort, FileSystemPort, GitignorePort, ManifestPort, McpPort};
use crate::domain::agent::{AgentDefinition, all_agents};
use crate::domain::config::LoadedConfig;
use crate::domain::constants::{GENERATED_BY_IMRULE_MARKER, IMRULE_CACHE_PATH, LEGACY_DIR_NAME};
use crate::domain::error::ImruleError;
use crate::domain::manifest::ApplyManifest;
use crate::domain::mcp::is_native_mcp_content_empty;
use crate::domain::skills::get_skills_gitignore_paths;
use crate::domain::subagent::subagents_gitignore_paths;

/// Runtime options for `imrule clear`.
#[derive(Debug, Clone)]
pub struct ClearOptions {
    pub project_root: PathBuf,
    pub agents: Option<Vec<String>>,
    pub config: Option<PathBuf>,
    pub dry_run: bool,
    /// Also remove the `.imrule/` source directory.
    pub remove_source: bool,
}

/// Clear use case: removes all assets generated by `imrule apply`.
pub struct ClearUseCase<'a> {
    config_port: &'a dyn ConfigPort,
    fs_port: &'a dyn FileSystemPort,
    gitignore_port: &'a dyn GitignorePort,
    mcp_port: &'a dyn McpPort,
    manifest_port: Option<&'a dyn ManifestPort>,
}

impl<'a> ClearUseCase<'a> {
    pub fn new(
        config_port: &'a dyn ConfigPort,
        fs_port: &'a dyn FileSystemPort,
        gitignore_port: &'a dyn GitignorePort,
        mcp_port: &'a dyn McpPort,
    ) -> Self {
        Self {
            config_port,
            fs_port,
            gitignore_port,
            mcp_port,
            manifest_port: None,
        }
    }

    /// Lets clear reach outputs the current configuration no longer describes —
    /// MCP servers deleted from `imrule.toml` after they were propagated, for
    /// instance — by consulting what the last apply recorded.
    pub fn with_manifest(mut self, manifest_port: &'a dyn ManifestPort) -> Self {
        self.manifest_port = Some(manifest_port);
        self
    }

    /// Removes all imrule-generated files for selected agents.
    pub fn execute(&self, options: ClearOptions) -> Result<Vec<PathBuf>, ImruleError> {
        tracing::info!(
            project_root = %options.project_root.display(),
            dry_run = options.dry_run,
            remove_source = options.remove_source,
            "starting clear"
        );
        let config = self.config_port.load_config(
            &options.project_root,
            options.config.as_deref(),
            options.agents.clone(),
        )?;
        // clear defaults to ALL agents regardless of agents config.
        // Only respect --agents when the user explicitly targets specific agents.
        let selected_agents = match options.agents.as_deref() {
            Some(agents) => resolve_selected_agents(&config, Some(agents))?,
            None => all_agents(),
        };

        // Collect MCP keys before any deletion so native configs can be cleaned.
        // The current config only describes servers that still exist; the last
        // apply's manifest also names the ones since deleted from it, which are
        // exactly the ones that would otherwise stay orphaned in agent configs.
        // `--agents` narrows a clear to the agents named, so the manifest — which
        // spans every agent — is only safe to act on for a full clear.
        let full_clear = options.agents.is_none();
        let manifest = match (full_clear, self.manifest_port) {
            (true, Some(port)) => port.read_manifest(&options.project_root)?,
            _ => None,
        };
        let mut imrule_mcp_keys = self.collect_mcp_keys(&options.project_root, &config)?;
        if let Some(manifest) = &manifest {
            imrule_mcp_keys.extend(manifest.mcp_servers.iter().cloned());
            imrule_mcp_keys.sort();
            imrule_mcp_keys.dedup();
        }

        // Resolve output paths using the same logic as apply (respects custom output_path from config).
        let output_paths =
            get_resolved_output_paths(&options.project_root, &selected_agents, &config);
        let mut removed = Vec::new();

        // Remove generated rule files and their backups.
        let removal_results: Result<Vec<_>, ImruleError> = output_paths
            .par_iter()
            .map(|path| {
                let mut local_removed = Vec::new();
                if self.remove_if_generated(path, options.dry_run)? {
                    local_removed.push(path.clone());
                }
                self.remove_backup(path, options.dry_run)?;
                Ok(local_removed)
            })
            .collect();
        removed.extend(removal_results?.into_iter().flatten());

        // Remove subagent directories created by imrule apply.
        self.clear_subagents(&options, &selected_agents, &mut removed)?;

        // Remove entire agent skills root directories (created by imrule apply).
        self.clear_skills(&options, &selected_agents, &mut removed)?;

        // Remove imrule-managed keys from native MCP configs and delete empty ones.
        self.clear_mcp_configs(&options, &selected_agents, &imrule_mcp_keys, &mut removed)?;

        // Also clean the exact files the last apply wrote. `get_native_mcp_path`
        // resolves today's preferred location, which can differ from where an
        // earlier version wrote, and an agent dropped from the config is not in
        // `selected_agents` at all when `--agents` narrows the run.
        if let Some(manifest) = &manifest {
            self.clear_recorded_mcp_targets(&options, manifest, &imrule_mcp_keys, &mut removed)?;
        }

        // Prune empty parent directories left after all file removals.
        if !options.dry_run {
            for path in &output_paths {
                if let Some(parent) = path.parent() {
                    self.prune_empty_parents(parent, &options.project_root)?;
                }
            }
        }

        // Clear the imrule-managed gitignore block.
        if !options.dry_run {
            self.gitignore_port
                .update_gitignore(&options.project_root, &[], ".gitignore")?;
        }

        // Drop the apply state files: with every generated asset gone there is
        // nothing left for them to describe. A narrowed clear leaves them, since
        // the agents it skipped still have assets the manifest accounts for.
        if !options.dry_run && full_clear {
            if let Some(port) = self.manifest_port {
                port.remove_manifest(&options.project_root)?;
            }
            let cache = options.project_root.join(IMRULE_CACHE_PATH);
            if self.fs_port.file_exists(&cache) {
                self.fs_port.remove_file(&cache)?;
                removed.push(cache);
            }
        }

        // Optionally remove .imrule/ (and legacy .ruler/) source directories.
        if options.remove_source {
            for dir_name in [".imrule", LEGACY_DIR_NAME] {
                let dir = options.project_root.join(dir_name);
                if self.fs_port.file_exists(&dir) {
                    if !options.dry_run {
                        self.fs_port.remove_dir_all(&dir)?;
                    }
                    removed.push(dir);
                }
            }
        }

        tracing::info!(removed_count = removed.len(), "clear completed");
        Ok(removed)
    }

    fn clear_subagents(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        for dir in subagents_gitignore_paths(&options.project_root, selected_agents) {
            if self.fs_port.file_exists(&dir) {
                if !options.dry_run {
                    self.fs_port.remove_dir_all(&dir)?;
                    if let Some(parent) = dir.parent() {
                        self.prune_empty_parents(parent, &options.project_root)?;
                    }
                }
                removed.push(dir);
            }
        }
        Ok(())
    }

    fn clear_skills(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        for skills_root in get_skills_gitignore_paths(&options.project_root, selected_agents) {
            if self.fs_port.file_exists(&skills_root) {
                if !options.dry_run {
                    self.fs_port.remove_dir_all(&skills_root)?;
                    self.prune_empty_parents(
                        skills_root.parent().unwrap_or(&skills_root),
                        &options.project_root,
                    )?;
                }
                removed.push(skills_root);
            }
        }

        // Undo the GJC skill-discovery enablement written by apply.
        self.clear_gjc_skill_config(options, selected_agents, removed)?;

        Ok(())
    }

    /// Strips ImRule-managed keys from `.gjc/config.yml`, deleting the file when
    /// nothing meaningful remains. Only runs when gjc is among the selected
    /// agents so `clear --agents <others>` leaves the GJC config untouched.
    fn clear_gjc_skill_config(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        let gjc_selected = selected_agents
            .iter()
            .any(|agent| agent.identifier == "gjc" && agent.capabilities.native_skills);
        if !gjc_selected {
            return Ok(());
        }

        let config_path = options
            .project_root
            .join(crate::domain::constants::GJC_CONFIG_PATH);
        if !self.fs_port.file_exists(&config_path) {
            return Ok(());
        }

        if options.dry_run {
            removed.push(config_path);
            return Ok(());
        }

        let existing = self.fs_port.read_text(&config_path)?;
        match crate::domain::gjc_config::strip_gjc_skill_discovery(&existing)? {
            Some(remaining) => {
                self.fs_port
                    .write_text(&config_path, &remaining)
                    .map_err(|e| {
                        ImruleError::skills(format!("failed to rewrite .gjc/config.yml: {e}"))
                    })?;
            }
            None => {
                self.fs_port.remove_file(&config_path)?;
                if let Some(parent) = config_path.parent() {
                    self.prune_empty_parents(parent, &options.project_root)?;
                }
                removed.push(config_path);
            }
        }
        Ok(())
    }

    fn clear_mcp_configs(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        imrule_mcp_keys: &[String],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        if imrule_mcp_keys.is_empty() {
            return Ok(());
        }
        for agent in selected_agents {
            // NOTE: do NOT gate on agent_supports_mcp here. An agent whose MCP
            // capability was later disabled (e.g. Windsurf) may still have a
            // native MCP file from a previous apply; clear must remove imrule's
            // keys from it instead of orphaning them. Agents with no native MCP
            // path are skipped below anyway.
            let Some(native_path) = self
                .mcp_port
                .get_native_mcp_path(agent.name, &options.project_root)
            else {
                continue;
            };
            // The keys to strip may come from a manifest a repository shipped,
            // so never rewrite a config linked to a file outside the project.
            if !self.fs_port.file_exists(&native_path)
                || !self
                    .fs_port
                    .target_resolves_within(&native_path, &options.project_root)
            {
                continue;
            }
            if options.dry_run {
                removed.push(native_path);
                continue;
            }
            self.remove_mcp_keys(&native_path, agent.mcp_server_key, imrule_mcp_keys)?;
            self.remove_mcp_file_if_empty(&native_path)?;
            removed.push(native_path.clone());
            if let Some(parent) = native_path.parent() {
                self.prune_empty_parents(parent, &options.project_root)?;
            }
        }
        Ok(())
    }

    /// Strips imrule-managed keys from the native MCP files the last apply
    /// actually wrote, whatever the current config says about them.
    fn clear_recorded_mcp_targets(
        &self,
        options: &ClearOptions,
        manifest: &ApplyManifest,
        imrule_mcp_keys: &[String],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        if imrule_mcp_keys.is_empty() {
            return Ok(());
        }
        for target in &manifest.mcp_targets {
            let native_path = options.project_root.join(&target.path);
            // The manifest may come from a cloned repository: never rewrite a
            // config that resolves, through `..` or a link, outside the project.
            if !self.fs_port.file_exists(&native_path)
                || !self
                    .fs_port
                    .target_resolves_within(&native_path, &options.project_root)
            {
                continue;
            }
            if removed.contains(&native_path) {
                continue;
            }
            if options.dry_run {
                removed.push(native_path);
                continue;
            }
            self.remove_mcp_keys(&native_path, &target.server_key, imrule_mcp_keys)?;
            self.remove_mcp_file_if_empty(&native_path)?;
            removed.push(native_path.clone());
            if let Some(parent) = native_path.parent() {
                self.prune_empty_parents(parent, &options.project_root)?;
            }
        }
        Ok(())
    }

    fn remove_if_generated(&self, path: &Path, dry_run: bool) -> Result<bool, ImruleError> {
        let content = match self.fs_port.read_text(path) {
            Ok(c) => c,
            Err(_) => return Ok(false),
        };
        if !content.starts_with(GENERATED_BY_IMRULE_MARKER) {
            return Ok(false);
        }
        if !dry_run {
            self.fs_port.remove_file(path)?;
        }
        Ok(true)
    }

    fn remove_backup(&self, path: &Path, dry_run: bool) -> Result<(), ImruleError> {
        let mut bak = path.as_os_str().to_os_string();
        bak.push(".bak");
        let bak_path = PathBuf::from(bak);
        if self.fs_port.file_exists(&bak_path) && !dry_run {
            self.fs_port.remove_file(&bak_path)?;
        }
        Ok(())
    }

    /// Removes empty directories starting from `path` and walking up to (but not including) `stop_at`.
    fn prune_empty_parents(&self, path: &Path, stop_at: &Path) -> Result<(), ImruleError> {
        let mut dir = path.to_path_buf();
        while dir != stop_at && dir.starts_with(stop_at) {
            if !self.fs_port.remove_dir_if_empty(&dir)? {
                break;
            }
            if !dir.pop() {
                break;
            }
        }
        Ok(())
    }

    /// Collects every MCP server name that `apply` could have written into native
    /// agent configs. Servers come from two sources that `apply` unions together
    /// (see `build_imrule_mcp_config`): the legacy `.imrule/mcp.json` file and the
    /// `[mcp_servers]` table in `imrule.toml` (written by `imrule mcp add`). Both
    /// must be enumerated here, otherwise `clear` orphans TOML-defined servers in
    /// every agent config.
    fn collect_mcp_keys(
        &self,
        project_root: &Path,
        config: &LoadedConfig,
    ) -> Result<Vec<String>, ImruleError> {
        let mut keys: Vec<String> = Vec::new();

        // Source 1: legacy `.imrule/mcp.json`.
        if let Some(mcp_config) = self.mcp_port.read_imrule_mcp_config(project_root)? {
            if let Some(obj) = mcp_config.get("mcpServers").and_then(|s| s.as_object()) {
                keys.extend(obj.keys().cloned());
            }
        }

        // Source 2: `[mcp_servers]` table in `imrule.toml`.
        keys.extend(config.mcp_servers.keys().cloned());

        // De-duplicate while preserving order; a server may exist in both sources.
        keys.sort();
        keys.dedup();
        Ok(keys)
    }

    fn remove_mcp_keys(
        &self,
        native_path: &Path,
        server_key: &str,
        keys_to_remove: &[String],
    ) -> Result<(), ImruleError> {
        let mut config = self.mcp_port.read_native_mcp(native_path)?;
        let Some(obj) = config.as_object_mut() else {
            return Ok(());
        };
        for key_section in [server_key, "mcpServers"] {
            if let Some(servers) = obj.get_mut(key_section).and_then(|v| v.as_object_mut()) {
                for k in keys_to_remove {
                    servers.remove(k.as_str());
                }
            }
        }
        // Raw write: clear must only remove imrule-managed keys, never reshape
        // the user's own remaining servers (which write_native_mcp would do).
        self.mcp_port.write_native_mcp_raw(native_path, &config)
    }

    /// Removes a native MCP config file if it contains only empty objects/arrays.
    fn remove_mcp_file_if_empty(&self, native_path: &Path) -> Result<(), ImruleError> {
        if !self.fs_port.file_exists(native_path) {
            return Ok(());
        }
        let content = self.fs_port.read_text(native_path)?;
        if is_native_mcp_content_empty(&content) {
            self.fs_port.remove_file(native_path)?;
        }
        Ok(())
    }
}

/// Resolves output paths for all agents, respecting custom output_path from imrule.toml config.
/// Uses the same `instruction_output_path` function as apply to ensure custom paths are covered.
fn get_resolved_output_paths(
    project_root: &Path,
    agents: &[AgentDefinition],
    config: &LoadedConfig,
) -> Vec<PathBuf> {
    let mut seen = std::collections::BTreeSet::new();
    let mut paths = Vec::new();
    for agent in agents {
        let agent_config = config.agent_configs.get(agent.identifier);
        if let Some(path) = instruction_output_path(project_root, agent, agent_config) {
            if seen.insert(path.clone()) {
                paths.push(path);
            }
        }
    }
    paths
}
