//! Clear use case — removes all imrule-generated assets.

use std::path::{Path, PathBuf};

use crate::application::apply_use_case::{instruction_output_path, resolve_selected_agents};
use crate::application::ports::{ConfigPort, FileSystemPort, GitignorePort, McpPort};
use crate::domain::agent::{all_agents, AgentDefinition};
use crate::domain::config::LoadedConfig;
use crate::domain::constants::{
    CLAUDE_SUBAGENTS_PATH, CODEX_SUBAGENTS_PATH, COPILOT_SUBAGENTS_PATH, CURSOR_SUBAGENTS_PATH,
    GENERATED_BY_IMRULE_MARKER, LEGACY_DIR_NAME,
};
use crate::domain::error::ImruleError;
use crate::domain::mcp::agent_supports_mcp;

/// Runtime options for `imrule clear`.
#[derive(Debug, Clone)]
pub struct ClearOptions {
    pub project_root: PathBuf,
    pub agents: Option<Vec<String>>,
    pub config: Option<PathBuf>,
    pub dry_run: bool,
    /// Also remove the `.imrule/` source directory.
    pub remove_source: bool,
}

/// Clear use case: removes all assets generated by `imrule apply`.
pub struct ClearUseCase<'a> {
    config_port: &'a dyn ConfigPort,
    fs_port: &'a dyn FileSystemPort,
    gitignore_port: &'a dyn GitignorePort,
    mcp_port: &'a dyn McpPort,
}

impl<'a> ClearUseCase<'a> {
    pub fn new(
        config_port: &'a dyn ConfigPort,
        fs_port: &'a dyn FileSystemPort,
        gitignore_port: &'a dyn GitignorePort,
        mcp_port: &'a dyn McpPort,
    ) -> Self {
        Self {
            config_port,
            fs_port,
            gitignore_port,
            mcp_port,
        }
    }

    /// Removes all imrule-generated files for selected agents.
    pub fn execute(&self, options: ClearOptions) -> Result<Vec<PathBuf>, ImruleError> {
        let config = self.config_port.load_config(
            &options.project_root,
            options.config.as_deref(),
            options.agents.clone(),
        )?;
        // clear defaults to ALL agents regardless of default_agents config.
        // Only respect --agents when the user explicitly targets specific agents.
        let selected_agents = match options.agents.as_deref() {
            Some(agents) => resolve_selected_agents(&config, Some(agents))?,
            None => all_agents(),
        };

        // Collect MCP keys before any deletion so native configs can be cleaned.
        let imrule_mcp_keys = self.collect_mcp_keys(&options.project_root)?;

        // Resolve output paths using the same logic as apply (respects custom output_path from config).
        let output_paths =
            get_resolved_output_paths(&options.project_root, &selected_agents, &config);
        let mut removed = Vec::new();

        // Remove generated rule files and their backups.
        for path in &output_paths {
            if self.remove_if_generated(path, options.dry_run)? {
                removed.push(path.clone());
            }
            self.remove_backup(path, options.dry_run)?;
        }

        // Remove subagent directories created by imrule apply.
        self.clear_subagents(&options, &selected_agents, &mut removed)?;

        // Remove entire agent skills root directories (created by imrule apply).
        self.clear_skills(&options, &selected_agents, &mut removed)?;

        // Remove imrule-managed keys from native MCP configs and delete empty ones.
        self.clear_mcp_configs(&options, &selected_agents, &imrule_mcp_keys, &mut removed)?;

        // Prune empty parent directories left after all file removals.
        if !options.dry_run {
            for path in &output_paths {
                if let Some(parent) = path.parent() {
                    self.prune_empty_parents(parent, &options.project_root)?;
                }
            }
        }

        // Clear the imrule-managed gitignore block.
        if !options.dry_run {
            self.gitignore_port
                .update_gitignore(&options.project_root, &[], ".gitignore")?;
        }

        // Optionally remove .imrule/ (and legacy .ruler/) source directories.
        if options.remove_source {
            for dir_name in [".imrule", LEGACY_DIR_NAME] {
                let dir = options.project_root.join(dir_name);
                if self.fs_port.file_exists(&dir) {
                    if !options.dry_run {
                        self.fs_port.remove_dir_all(&dir)?;
                    }
                    removed.push(dir);
                }
            }
        }

        Ok(removed)
    }

    fn clear_subagents(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        let subagent_targets: &[(&str, &str)] = &[
            ("claude", CLAUDE_SUBAGENTS_PATH),
            ("cursor", CURSOR_SUBAGENTS_PATH),
            ("codex", CODEX_SUBAGENTS_PATH),
            ("copilot", COPILOT_SUBAGENTS_PATH),
        ];

        let selected_ids: std::collections::BTreeSet<&str> = selected_agents
            .iter()
            .filter(|a| a.capabilities.native_subagents)
            .map(|a| a.identifier)
            .collect();

        let mut seen = std::collections::BTreeSet::new();
        for (id, rel_path) in subagent_targets {
            if !selected_ids.contains(id) {
                continue;
            }
            let dir = options.project_root.join(rel_path);
            let key = dir.to_string_lossy().to_string();
            if !seen.insert(key) {
                continue;
            }
            if self.fs_port.file_exists(&dir) {
                if !options.dry_run {
                    self.fs_port.remove_dir_all(&dir)?;
                    if let Some(parent) = dir.parent() {
                        self.prune_empty_parents(parent, &options.project_root)?;
                    }
                }
                removed.push(dir);
            }
        }
        Ok(())
    }

    fn clear_skills(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        for skills_root in self.collect_skills_dirs(&options.project_root, selected_agents) {
            if self.fs_port.file_exists(&skills_root) {
                if !options.dry_run {
                    self.fs_port.remove_dir_all(&skills_root)?;
                    self.prune_empty_parents(
                        skills_root.parent().unwrap_or(&skills_root),
                        &options.project_root,
                    )?;
                }
                removed.push(skills_root);
            }
        }
        Ok(())
    }

    fn clear_mcp_configs(
        &self,
        options: &ClearOptions,
        selected_agents: &[AgentDefinition],
        imrule_mcp_keys: &[String],
        removed: &mut Vec<PathBuf>,
    ) -> Result<(), ImruleError> {
        if imrule_mcp_keys.is_empty() {
            return Ok(());
        }
        for agent in selected_agents {
            if !agent_supports_mcp(agent) {
                continue;
            }
            let Some(native_path) = self
                .mcp_port
                .get_native_mcp_path(agent.name, &options.project_root)
            else {
                continue;
            };
            if !self.fs_port.file_exists(&native_path) {
                continue;
            }
            if options.dry_run {
                removed.push(native_path);
                continue;
            }
            self.remove_mcp_keys(&native_path, agent.mcp_server_key, imrule_mcp_keys)?;
            self.remove_mcp_file_if_empty(&native_path)?;
            removed.push(native_path.clone());
            if let Some(parent) = native_path.parent() {
                self.prune_empty_parents(parent, &options.project_root)?;
            }
        }
        Ok(())
    }

    fn remove_if_generated(&self, path: &Path, dry_run: bool) -> Result<bool, ImruleError> {
        if !self.fs_port.file_exists(path) {
            return Ok(false);
        }
        let content = self.fs_port.read_text(path)?;
        if !content.starts_with(GENERATED_BY_IMRULE_MARKER) {
            return Ok(false);
        }
        if !dry_run {
            self.fs_port.remove_file(path)?;
        }
        Ok(true)
    }

    fn remove_backup(&self, path: &Path, dry_run: bool) -> Result<(), ImruleError> {
        let mut bak = path.as_os_str().to_os_string();
        bak.push(".bak");
        let bak_path = PathBuf::from(bak);
        if self.fs_port.file_exists(&bak_path) && !dry_run {
            self.fs_port.remove_file(&bak_path)?;
        }
        Ok(())
    }

    /// Removes empty directories starting from `path` and walking up to (but not including) `stop_at`.
    fn prune_empty_parents(&self, path: &Path, stop_at: &Path) -> Result<(), ImruleError> {
        let mut dir = path.to_path_buf();
        while dir != stop_at && dir.starts_with(stop_at) {
            if !self.fs_port.remove_dir_if_empty(&dir)? {
                break;
            }
            if !dir.pop() {
                break;
            }
        }
        Ok(())
    }

    fn collect_skills_dirs(&self, project_root: &Path, agents: &[AgentDefinition]) -> Vec<PathBuf> {
        let agent_skill_paths: &[(&str, &str)] = &[
            ("claude", crate::domain::constants::CLAUDE_SKILLS_PATH),
            ("copilot", crate::domain::constants::CLAUDE_SKILLS_PATH),
            ("kilocode", crate::domain::constants::CLAUDE_SKILLS_PATH),
            ("codex", crate::domain::constants::CODEX_SKILLS_PATH),
            ("opencode", crate::domain::constants::OPENCODE_SKILLS_PATH),
            ("pi", crate::domain::constants::PI_SKILLS_PATH),
            ("goose", crate::domain::constants::GOOSE_SKILLS_PATH),
            ("amp", crate::domain::constants::GOOSE_SKILLS_PATH),
            ("mistral", crate::domain::constants::VIBE_SKILLS_PATH),
            ("roo", crate::domain::constants::ROO_SKILLS_PATH),
            ("gemini-cli", crate::domain::constants::GEMINI_SKILLS_PATH),
            ("junie", crate::domain::constants::JUNIE_SKILLS_PATH),
            ("cursor", crate::domain::constants::CURSOR_SKILLS_PATH),
            ("windsurf", crate::domain::constants::WINDSURF_SKILLS_PATH),
            ("factory", crate::domain::constants::FACTORY_SKILLS_PATH),
            (
                "antigravity",
                crate::domain::constants::ANTIGRAVITY_SKILLS_PATH,
            ),
        ];

        let mut dirs = Vec::new();
        let mut seen = std::collections::BTreeSet::new();

        for agent in agents {
            if !agent.capabilities.native_skills {
                continue;
            }
            if let Some(&target_rel) = agent_skill_paths
                .iter()
                .find(|(id, _)| *id == agent.identifier)
                .map(|(_, path)| path)
            {
                let dir = project_root.join(target_rel);
                let key = dir.to_string_lossy().to_string();
                if seen.insert(key) {
                    dirs.push(dir);
                }
            }
        }
        dirs
    }

    fn collect_mcp_keys(&self, project_root: &Path) -> Result<Vec<String>, ImruleError> {
        let Some(mcp_config) = self.mcp_port.read_imrule_mcp_config(project_root)? else {
            return Ok(Vec::new());
        };
        let keys = mcp_config
            .get("mcpServers")
            .and_then(|s| s.as_object())
            .map(|obj| obj.keys().cloned().collect())
            .unwrap_or_default();
        Ok(keys)
    }

    fn remove_mcp_keys(
        &self,
        native_path: &Path,
        server_key: &str,
        keys_to_remove: &[String],
    ) -> Result<(), ImruleError> {
        let mut config = self.mcp_port.read_native_mcp(native_path)?;
        let Some(obj) = config.as_object_mut() else {
            return Ok(());
        };
        for key_section in [server_key, "mcpServers"] {
            if let Some(servers) = obj.get_mut(key_section).and_then(|v| v.as_object_mut()) {
                for k in keys_to_remove {
                    servers.remove(k.as_str());
                }
            }
        }
        self.mcp_port.write_native_mcp(native_path, &config)
    }

    /// Removes a native MCP config file if it contains only empty objects/arrays.
    fn remove_mcp_file_if_empty(&self, native_path: &Path) -> Result<(), ImruleError> {
        if !self.fs_port.file_exists(native_path) {
            return Ok(());
        }
        let content = self.fs_port.read_text(native_path)?;
        if let Ok(val) = serde_json::from_str::<serde_json::Value>(&content) {
            if is_json_effectively_empty(&val) {
                self.fs_port.remove_file(native_path)?;
            }
        }
        Ok(())
    }
}

/// Returns true if a JSON value contains no meaningful data (only empty objects/arrays/nulls).
fn is_json_effectively_empty(val: &serde_json::Value) -> bool {
    match val {
        serde_json::Value::Null => true,
        serde_json::Value::Object(map) => {
            map.is_empty() || map.values().all(is_json_effectively_empty)
        }
        serde_json::Value::Array(arr) => arr.is_empty(),
        _ => false,
    }
}

/// Resolves output paths for all agents, respecting custom output_path from imrule.toml config.
/// Uses the same `instruction_output_path` function as apply to ensure custom paths are covered.
fn get_resolved_output_paths(
    project_root: &Path,
    agents: &[AgentDefinition],
    config: &LoadedConfig,
) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    for agent in agents {
        let agent_config = config.agent_configs.get(agent.identifier);
        if let Some(path) = instruction_output_path(project_root, agent, agent_config) {
            paths.push(path);
        }
    }
    paths
}
